var corinpapaStatements = [
  {
    "stock": "비트마인",
    "dirType": "sell",
    "headline": "저도 똑같은 서학개미였고 제 거의 모든 포트폴리오가 이더리움과 비트마인에 몰빵을 했었죠.....",
    "quote": "저도 똑같은 서학개미였고 제 거의 모든 포트폴리오가 이더리움과 비트마인에 몰빵을 했었죠... 저는 손절을 했거든요. 네. 마이너스 뭐 엄청나게 봤습니다. 엄청나게 손절을 했는데도 불구하고",
    "detail": "화자가 비트마인에 올인했다가 큰 손실로 손절했다고 고백. 피터 틸이 3개월 만에 절반을 매각한 것을 비판하며 자신도 배신했다고 표현",
    "date": "2026-02-01",
    "ts": "8:52",
    "url": "https://www.youtube.com/watch?v=-brWAKvRaqI",
    "videoUrl": "https://www.youtube.com/watch?v=-brWAKvRaqI",
    "speaker": "코린이 아빠",
    "video_id": "-brWAKvRaqI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "이더륨에 대해서 공부를 더 해 보니까 스테이블 코인이 아무리 폭발해도 이더리움 상승이 일어...",
    "quote": "이더륨에 대해서 공부를 더 해 보니까 스테이블 코인이 아무리 폭발해도 이더리움 상승이 일어나지 않습니다. 절대로... 울트라 사운드 보니까 도대체 어떻게 가능하지라는 거를 계속해서 토론하다 보니까 아, 이거 어렵다. 이거 어렵다. 불가능하다",
    "detail": "화자가 이더리움의 울트라 사운드 머니 개념에 대해 깊이 연구한 결과 불가능하다는 결론에 도달했다고 설명",
    "date": "2026-02-01",
    "ts": "8:25",
    "url": "https://www.youtube.com/watch?v=-brWAKvRaqI",
    "videoUrl": "https://www.youtube.com/watch?v=-brWAKvRaqI",
    "speaker": "코린이 아빠",
    "video_id": "-brWAKvRaqI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더질라",
    "dirType": "buy",
    "headline": "초반에 살 수 있으면 좀 도움이 될 것 같긴 합니다. 혹시 이거 나온다는 뉴스가 나오면 게...",
    "quote": "초반에 살 수 있으면 좀 도움이 될 것 같긴 합니다. 혹시 이거 나온다는 뉴스가 나오면 게시판에 빨리 올려 주세요. 초반에 사면 괜찮을 수도 있을 것 같아요.",
    "detail": "화자가 피터틸의 유사한 투자 패턴이 반복될 경우 초반 매수에 대한 조건부 긍정적 전망을 제시",
    "date": "2025-08-15",
    "ts": "5:57",
    "url": "https://www.youtube.com/watch?v=-fmfJn1psbA",
    "videoUrl": "https://www.youtube.com/watch?v=-fmfJn1psbA",
    "speaker": "코린이 아빠",
    "video_id": "-fmfJn1psbA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "피터틸 사단은 이더리움에 대해서는 정말 진심이다. 진심이다. 네. 정말 매집하고 독점하려는...",
    "quote": "피터틸 사단은 이더리움에 대해서는 정말 진심이다. 진심이다. 네. 정말 매집하고 독점하려는 그런 야이 불타오르는 거 같습니다.",
    "detail": "피터틸과 관련 투자자들의 이더리움에 대한 강한 투자 의지를 분석하며 장기적 긍정 전망 표현",
    "date": "2025-08-15",
    "ts": "7:11",
    "url": "https://www.youtube.com/watch?v=-fmfJn1psbA",
    "videoUrl": "https://www.youtube.com/watch?v=-fmfJn1psbA",
    "speaker": "코린이 아빠",
    "video_id": "-fmfJn1psbA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "concern",
    "headline": "절대로 한 방에 들어가지 마세요. 정말로 이거는 분할해 조금씩 조금씩만 하세요.",
    "quote": "절대로 한 방에 들어가지 마세요. 정말로 이거는 분할해 조금씩 조금씩만 하세요.",
    "detail": "화자가 캔톤네트워크(CC)에 대해 투자 시 주의사항을 강조하며 한번에 많은 금액을 투자하지 말고 분할매수를 권하고 있음",
    "date": "2025-12-03",
    "ts": "0:46",
    "url": "https://www.youtube.com/watch?v=08FEwaGddCk",
    "videoUrl": "https://www.youtube.com/watch?v=08FEwaGddCk",
    "speaker": "코린이 아빠",
    "video_id": "08FEwaGddCk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "저는 7월 달에 이미 이더륨으로 옮기기 시작을 했고 그다음에 비트마인이라 회사가 아, 이더...",
    "quote": "저는 7월 달에 이미 이더륨으로 옮기기 시작을 했고 그다음에 비트마인이라 회사가 아, 이더리 매집 회사라는 거에 나오자마자 저는 바로 한 다음에 영상을 올려 드렸죠. 그래서 바로 매집을 했습니다.",
    "detail": "화자가 7월부터 이더리움으로 포트폴리오를 이동하기 시작했고, 비트마인의 이더리움 매집 소식에 바로 반응하여 매수했다고 밝힘",
    "date": "2025-11-08",
    "ts": "5:28",
    "url": "https://www.youtube.com/watch?v=0XEv66hwKqA",
    "videoUrl": "https://www.youtube.com/watch?v=0XEv66hwKqA",
    "speaker": "코린이 아빠",
    "video_id": "0XEv66hwKqA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "strong_buy",
    "headline": "저는 단 한 번도 익절하지 못한 저는 광신도입니다. BMR이 70달러를 넘었을 때도 64달...",
    "quote": "저는 단 한 번도 익절하지 못한 저는 광신도입니다. BMR이 70달러를 넘었을 때도 64달러 65달러를 갔을 때도 한 번 두 번 세 번 기회가 있었죠.",
    "detail": "화자가 자신을 '광신도'라고 표현하며 고점에서도 매도하지 않았음을 밝힘. 강력한 장기 홀딩 의지와 확신을 보여줌",
    "date": "2025-11-08",
    "ts": "6:17",
    "url": "https://www.youtube.com/watch?v=0XEv66hwKqA",
    "videoUrl": "https://www.youtube.com/watch?v=0XEv66hwKqA",
    "speaker": "코린이 아빠",
    "video_id": "0XEv66hwKqA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "아직 2026년이고 RWA해는 시작도 안 했습니다. 누군가는 가격을 보지만 누군가는 미래의...",
    "quote": "아직 2026년이고 RWA해는 시작도 안 했습니다. 누군가는 가격을 보지만 누군가는 미래의 가치를 바라봅니다.",
    "detail": "2026년 RWA 상승장에서 캔톤의 미래 가치에 대한 강한 확신 표현",
    "date": "2025-12-30",
    "ts": "7:02",
    "url": "https://www.youtube.com/watch?v=151ejJicjy4",
    "videoUrl": "https://www.youtube.com/watch?v=151ejJicjy4",
    "speaker": "코린이 아빠",
    "video_id": "151ejJicjy4",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "타르",
    "dirType": "positive",
    "headline": "왜 다른 자산들은 마이너스인데 타임윤만 슬금슬금 오르지? 슬금슬금 오릅니다.",
    "quote": "왜 다른 자산들은 마이너스인데 타임윤만 슬금슬금 오르지? 슬금슬금 오릅니다.",
    "detail": "타임윤(THAR)이 다른 자산들과 달리 조용히 상승세를 보이고 있다는 관찰",
    "date": "2025-12-30",
    "ts": "4:18",
    "url": "https://www.youtube.com/watch?v=151ejJicjy4",
    "videoUrl": "https://www.youtube.com/watch?v=151ejJicjy4",
    "speaker": "코린이 아빠",
    "video_id": "151ejJicjy4",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "비트마인이 이더리움의 금고가 된다. 디지털 금융 인프라의 전략적 비축 자산으로 보는 거예요...",
    "quote": "비트마인이 이더리움의 금고가 된다. 디지털 금융 인프라의 전략적 비축 자산으로 보는 거예요. 앞으로 미래 금융에 5% 정도는 우리가 쭉 비축을 하고 가야 된다",
    "detail": "비트마인의 이더리움 5% 지분 확보 전략을 피터 틸의 관점에서 긍정적으로 분석",
    "date": "2025-07-29",
    "ts": "5:45",
    "url": "https://www.youtube.com/watch?v=1l9mMgFjixk",
    "videoUrl": "https://www.youtube.com/watch?v=1l9mMgFjixk",
    "speaker": "코린이 아빠",
    "video_id": "1l9mMgFjixk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "그중에 대표주자가 이더리움이죠. USDC의 90% 이상이 이더리움입니다",
    "quote": "그중에 대표주자가 이더리움이죠. USDC의 90% 이상이 이더리움입니다",
    "detail": "크립토 3법에서 4년 이상 유지된 탈중앙화 블록체인 기준을 통과할 수 있는 대표적 블록체인으로 이더리움을 언급",
    "date": "2025-07-29",
    "ts": "5:07",
    "url": "https://www.youtube.com/watch?v=1l9mMgFjixk",
    "videoUrl": "https://www.youtube.com/watch?v=1l9mMgFjixk",
    "speaker": "코린이 아빠",
    "video_id": "1l9mMgFjixk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "concern",
    "headline": "출렁이는 파도가 두렵다면 BMR에 탑승하시면 안 됩니다. 좀 더 안전한 대로 가세요.",
    "quote": "출렁이는 파도가 두렵다면 BMR에 탑승하시면 안 됩니다. 좀 더 안전한 대로 가세요.",
    "detail": "비트마인의 변동성과 위험성을 경고하며, 리스크를 감당할 수 없다면 투자하지 말라고 조언",
    "date": "2025-08-04",
    "ts": "3:52",
    "url": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "videoUrl": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "speaker": "코린이 아빠",
    "video_id": "2wdlIAF0OrA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "엔비디아",
    "dirType": "buy",
    "headline": "뭐 엔비디아나 아니면 팔란티어도 좋은 대답 답이 될 수 있어요. 왜냐면 뭐 고가이긴 하지만...",
    "quote": "뭐 엔비디아나 아니면 팔란티어도 좋은 대답 답이 될 수 있어요. 왜냐면 뭐 고가이긴 하지만 계속 올라갈 겁니다.",
    "detail": "비트마인 대신 안전한 투자처로 엔비디아 추천, 고가지만 지속 상승 전망",
    "date": "2025-08-04",
    "ts": "3:56",
    "url": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "videoUrl": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "speaker": "코린이 아빠",
    "video_id": "2wdlIAF0OrA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "팔란티어",
    "dirType": "buy",
    "headline": "뭐 엔비디아나 아니면 팔란티어도 좋은 대답 답이 될 수 있어요. 왜냐면 뭐 고가이긴 하지만...",
    "quote": "뭐 엔비디아나 아니면 팔란티어도 좋은 대답 답이 될 수 있어요. 왜냐면 뭐 고가이긴 하지만 계속 올라갈 겁니다.",
    "detail": "비트마인 대신 안전한 투자처로 팔란티어 추천, 고가지만 지속 상승 전망",
    "date": "2025-08-04",
    "ts": "3:56",
    "url": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "videoUrl": "https://www.youtube.com/watch?v=2wdlIAF0OrA",
    "speaker": "코린이 아빠",
    "video_id": "2wdlIAF0OrA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "hold",
    "headline": "26년 2월에서 3월까지는 무조건 견딜 예정입니다. 결론부터 말씀드립니다.",
    "quote": "26년 2월에서 3월까지는 무조건 견딜 예정입니다. 결론부터 말씀드립니다.",
    "detail": "화자가 401K 관련 법안 시행과 연기금 자금 유입을 근거로 2026년 2-3월까지 홀딩 의지를 명확히 표현",
    "date": "2025-10-30",
    "ts": "3:52",
    "url": "https://www.youtube.com/watch?v=31dyiLfeqGk",
    "videoUrl": "https://www.youtube.com/watch?v=31dyiLfeqGk",
    "speaker": "코린이 아빠",
    "video_id": "31dyiLfeqGk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "hold",
    "headline": "26년 2월에서 3월까지는 무조건 견딜 예정입니다. 이더륨과 비트마인의 의무 복무 기간이다...",
    "quote": "26년 2월에서 3월까지는 무조건 견딜 예정입니다. 이더륨과 비트마인의 의무 복무 기간이다. 그래서 얼마든지 때려봐라. 묵묵히 담대하게 견뎌주마.",
    "detail": "화자가 본인 포트폴리오에서 비트마인이 꼴찌 수익률이지만 장기적 관점에서 홀딩 의지를 강하게 표현",
    "date": "2025-10-30",
    "ts": "8:41",
    "url": "https://www.youtube.com/watch?v=31dyiLfeqGk",
    "videoUrl": "https://www.youtube.com/watch?v=31dyiLfeqGk",
    "speaker": "코린이 아빠",
    "video_id": "31dyiLfeqGk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "concern",
    "headline": "아직도 이제 XRP의 기술력을 과신하는 사람들이 되게 많이 있는데 이게 해외에서 해외에서 ...",
    "quote": "아직도 이제 XRP의 기술력을 과신하는 사람들이 되게 많이 있는데 이게 해외에서 해외에서 이제 그 USDT를 보내 보잖아요.이 옵션이 10개가 넘습니다, 여러분. 10열 개가 넘어요. 그래서이 네트워크를 다 고를 수가 있는데 USDT를 송금을 하잖아요. 그러면 뭐 아비트럼도 있지만 플라즈마 이거 쓰면요. 여기 보세요. P가 예, 요금이 0.00. 예. 거의 무료입니다. 무료. 예. 무료예요. 예. 이것도 뭐 1달러가 안 되죠. 그래서 어떤 네트워크를 쓰든간에 요즘에 수수료가요 다 쌉니다. 네. 진짜 0.1달러 아니면 무료 수준이거든요. 그리고 속도는 어떠냐? XRP나 뭐 스텔라 루맨이나네 크게 차이가 없어요. 거 얘네도 금방 갑니다. 거의 1분이 안 걸려요. 거의 한 뭐 한 30초에서 1분 정도면 다 가거든요. 그렇기 때문에 얘네가 뭐 과거에 만들었던이 기술이 대단한 기술이 아니에요. 절대 여러분. 네. 다 할 수 있는 기술입니다.",
    "detail": "XRP의 기술적 우위가 더 이상 존재하지 않으며, 다른 네트워크들도 비슷한 속도와 낮은 수수료를 제공한다고 분석하며 XRP 기술력 과신에 대해 경고",
    "date": "2025-12-01",
    "ts": "6:20",
    "url": "https://www.youtube.com/watch?v=4uNZBw852Do",
    "videoUrl": "https://www.youtube.com/watch?v=4uNZBw852Do",
    "speaker": "코린이 아빠",
    "video_id": "4uNZBw852Do",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "타르",
    "dirType": "buy",
    "headline": "저는 네. 당연히이 블록체인과이 CC코인과이 매집 회사에 투자를 강행했습니다. 했어요. 네...",
    "quote": "저는 네. 당연히이 블록체인과이 CC코인과이 매집 회사에 투자를 강행했습니다. 했어요. 네. 포션은 뭐 제가 정확하게 말씀드릴 순 없지만 어떻든 지금 포션을 저는 늘려가고 있는 중입니다.",
    "detail": "캐시우드가 타르에 5억 4천만 달러를 투자한 이유를 분석하며, 월스트리트가 RWA를 퍼블릭 체인에 양보할 생각이 없다는 판단 하에 CC코인 매집 회사인 타르에 본인도 투자했다고 밝힘",
    "date": "2025-12-02",
    "ts": "11:56",
    "url": "https://www.youtube.com/watch?v=5HFHld3F5as",
    "videoUrl": "https://www.youtube.com/watch?v=5HFHld3F5as",
    "speaker": "코린이 아빠",
    "video_id": "5HFHld3F5as",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "CC 코인은이 기관들이이 거래를 할 때 사용되는 네트워크 수수료 코인입니다. 네. 그래서 ...",
    "quote": "CC 코인은이 기관들이이 거래를 할 때 사용되는 네트워크 수수료 코인입니다. 네. 그래서 이게 예측 가능한 수수료 구조이기 때문에 그래요.",
    "detail": "CC코인의 기술적 구조와 기관 친화적 특성을 설명하며, 예측 가능한 수수료 구조와 시장 가치를 정직하게 반영하는 설계에 대해 긍정적으로 평가",
    "date": "2025-12-02",
    "ts": "7:51",
    "url": "https://www.youtube.com/watch?v=5HFHld3F5as",
    "videoUrl": "https://www.youtube.com/watch?v=5HFHld3F5as",
    "speaker": "코린이 아빠",
    "video_id": "5HFHld3F5as",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "MP머티리얼즈",
    "dirType": "positive",
    "headline": "MP 머티리얼즈라는 회사가 최근에 1년 동안 주가가 227% 올랐더라고요. 그래서 히토류 ...",
    "quote": "MP 머티리얼즈라는 회사가 최근에 1년 동안 주가가 227% 올랐더라고요. 그래서 히토류 기업이 지금 미국에서 전략적으로 키우려고 하기 때문에 적국 매수 적국 매수로 뜨는 거죠.",
    "detail": "미국 내 유일한 희토류 광산 소유 기업으로 미국이 전략적으로 육성하고 있어 주가가 급등했다는 사실 전달과 함께 긍정적 평가",
    "date": "2026-01-21",
    "ts": "9:29",
    "url": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "videoUrl": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "speaker": "코린이 아빠",
    "video_id": "5nfe_ZdUSoA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "라이나스히토류",
    "dirType": "positive",
    "headline": "여기도 1년 동안 136%가 예 올라갔죠. 이거는 미국 국방부하고 계약을 했고 그래서 거의...",
    "quote": "여기도 1년 동안 136%가 예 올라갔죠. 이거는 미국 국방부하고 계약을 했고 그래서 거의 중국을 대처할 수 있는 유일한 기업이라고 합니다. 그래서 뭐 적극 매수라고 하는데 요것도 한번 보시면은 예 괜찮은 기업인 거 같습니다.",
    "detail": "미국 국방부와 계약하고 중국 외 유일한 중희토류 생산 능력을 보유한 호주 기업으로 괜찮은 기업이라고 평가",
    "date": "2026-01-21",
    "ts": "10:21",
    "url": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "videoUrl": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "speaker": "코린이 아빠",
    "video_id": "5nfe_ZdUSoA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "저는네 나중에 이제 캔톤에서 어느 정도 수익이 창출이 되면 또 그거를 또 분산 투자를 나중...",
    "quote": "저는네 나중에 이제 캔톤에서 어느 정도 수익이 창출이 되면 또 그거를 또 분산 투자를 나중에 할 거거든요.",
    "detail": "화자가 캔톤에서 수익을 창출할 것이라는 확신을 표현하며 지속적 보유 의지 표명",
    "date": "2026-01-21",
    "ts": "10:36",
    "url": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "videoUrl": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "speaker": "코린이 아빠",
    "video_id": "5nfe_ZdUSoA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "알파벳",
    "dirType": "buy",
    "headline": "그래서 저도 예 나중에 예 여기도 이제 분산 투자 예 또 월앤 버핏도 투자를 했잖아요. 그...",
    "quote": "그래서 저도 예 나중에 예 여기도 이제 분산 투자 예 또 월앤 버핏도 투자를 했잖아요. 그래서 저는 이제 캔톤에서 쭉 수익을 얻으면 전 또 알파벳 또 들어갈려고 생각을 하고 있습니다.",
    "detail": "구글의 AI 기술과 신소재 개발 능력을 높이 평가하며 향후 투자 의향 표명. 워렌 버핏의 투자도 긍정적 근거로 제시",
    "date": "2026-01-21",
    "ts": "14:11",
    "url": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "videoUrl": "https://www.youtube.com/watch?v=5nfe_ZdUSoA",
    "speaker": "코린이 아빠",
    "video_id": "5nfe_ZdUSoA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이더륨의 상승도 지금 불장 초기라는 생각이 듭니다",
    "quote": "이더륨의 상승도 지금 불장 초기라는 생각이 듭니다",
    "detail": "현재를 불장 초기로 보며 이더리움의 상승 가능성을 긍정적으로 전망",
    "date": "2025-07-19",
    "ts": "4:36",
    "url": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "videoUrl": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "speaker": "코린이 아빠",
    "video_id": "5rcYk9nhmMU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "buy",
    "headline": "저는 어 리스크를 즐기기 때문에 네. 어, 비트마인 이모션 테크놀로지스에 좀 투자를 했어요",
    "quote": "저는 어 리스크를 즐기기 때문에 네. 어, 비트마인 이모션 테크놀로지스에 좀 투자를 했어요",
    "detail": "화자가 피터틸의 투자와 연결하여 자신도 비트마인에 투자했다고 밝힘",
    "date": "2025-07-19",
    "ts": "4:01",
    "url": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "videoUrl": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "speaker": "코린이 아빠",
    "video_id": "5rcYk9nhmMU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "concern",
    "headline": "지금 XRP에 너무 편중돼 있어요. XRP가 저 너무 지분율이 너무 많습니다... 약간 리...",
    "quote": "지금 XRP에 너무 편중돼 있어요. XRP가 저 너무 지분율이 너무 많습니다... 약간 리스크가 있다고 생각이 돼요",
    "detail": "자신의 포트폴리오에서 XRP 비중이 과도하게 높아 리스크를 우려",
    "date": "2025-07-19",
    "ts": "4:17",
    "url": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "videoUrl": "https://www.youtube.com/watch?v=5rcYk9nhmMU",
    "speaker": "코린이 아빠",
    "video_id": "5rcYk9nhmMU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더질라",
    "dirType": "strong_sell",
    "headline": "이더질라는 제가 볼 땐 끝났다라고 생각이 됩니다",
    "quote": "이더질라는 제가 볼 땐 끝났다라고 생각이 됩니다",
    "detail": "이더질라가 이더리움 매집을 포기하고 RWA로 전환하면서 서브프라임 대출채권, 온라인 카지노 등 의심스러운 사업으로 방향을 바꾸는 것에 대해 부정적 평가",
    "date": "2025-12-23",
    "ts": "2:24",
    "url": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "videoUrl": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "speaker": "코린이 아빠",
    "video_id": "6IYiaHn6Jls",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "sell",
    "headline": "저는 이더리움 언스테이킹을 신청했습니다",
    "quote": "저는 이더리움 언스테이킹을 신청했습니다",
    "detail": "화자가 이더리움에서 완전히 빠지기 위해 언스테이킹을 신청하고 1이더리움 1국민 운동도 중단하겠다고 선언",
    "date": "2025-12-23",
    "ts": "5:14",
    "url": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "videoUrl": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "speaker": "코린이 아빠",
    "video_id": "6IYiaHn6Jls",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "저는 코인 시장의 흐름과 전혀 상관없이 움직이는 자산 제가 요즘에 계속 얘기하고 있는 캔톤...",
    "quote": "저는 코인 시장의 흐름과 전혀 상관없이 움직이는 자산 제가 요즘에 계속 얘기하고 있는 캔톤으로 저는 옮길 예정입니다",
    "detail": "시장과 독립적으로 움직이는 특성을 매력적으로 보며 이더리움에서 캔톤으로 자산을 이동할 예정이라고 발표",
    "date": "2025-12-23",
    "ts": "5:32",
    "url": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "videoUrl": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "speaker": "코린이 아빠",
    "video_id": "6IYiaHn6Jls",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "마이크로스트래티지",
    "dirType": "concern",
    "headline": "만약에 그게 마이너스로 돌아서게 되면 이제 압박이 엄청나게 더 심해지겠죠. 실제로 MSTR...",
    "quote": "만약에 그게 마이너스로 돌아서게 되면 이제 압박이 엄청나게 더 심해지겠죠. 실제로 MSTR의 비트코인을 시장에 던지기 시작하면 섬뜻한 제약이 몰려올 수도 있을 것 같습니다",
    "detail": "MSTR이 비트코인 매입 중단을 발표하고 주가가 순자산가치 대비 1배 수준까지 하락한 상황에서 추가 하락 시 비트코인 매도 압박 우려",
    "date": "2025-12-23",
    "ts": "4:50",
    "url": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "videoUrl": "https://www.youtube.com/watch?v=6IYiaHn6Jls",
    "speaker": "코린이 아빠",
    "video_id": "6IYiaHn6Jls",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "sell",
    "headline": "친구야 비트코인 던져라",
    "quote": "친구야 비트코인 던져라",
    "detail": "제목과 영상 첫머리에서 친구에게 비트코인을 던지라고(매도하라고) 직접 권유하는 발언. M2가 다른 곳으로 갔다는 논리로 뒷받침",
    "date": "2026-01-01",
    "ts": "0:03",
    "url": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "videoUrl": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "speaker": "코린이 아빠",
    "video_id": "6r5ZHidwBGs",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "엔비디아",
    "dirType": "positive",
    "headline": "엔비디아가 2024년도부터 반감기 때부터 지금까지... 시총이 그때 1.2조 달러였거든요....",
    "quote": "엔비디아가 2024년도부터 반감기 때부터 지금까지... 시총이 그때 1.2조 달러였거든요. 근데 26년 1월에 3.6조 달러입니다",
    "detail": "엔비디아의 실적을 긍정적으로 평가하며 유동성이 빅테크로 향하고 있다는 논리의 근거로 제시",
    "date": "2026-01-01",
    "ts": "3:36",
    "url": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "videoUrl": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "speaker": "코린이 아빠",
    "video_id": "6r5ZHidwBGs",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "금",
    "dirType": "positive",
    "headline": "시간이 지나고 보니까 가장 안전한 건 금이야",
    "quote": "시간이 지나고 보니까 가장 안전한 건 금이야",
    "detail": "러시아-우크라이나 전쟁 이후 안전자산으로서 금의 역할을 강조하며 중국의 금 매입 증가를 근거로 제시",
    "date": "2026-01-01",
    "ts": "10:07",
    "url": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "videoUrl": "https://www.youtube.com/watch?v=6r5ZHidwBGs",
    "speaker": "코린이 아빠",
    "video_id": "6r5ZHidwBGs",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "XRP 헤어질 결심",
    "quote": "XRP 헤어질 결심",
    "detail": "월드리버티파이낸셜이 USD1 스테이블코인으로 XRP의 국경간 송금 영역을 직접 대체하겠다고 선언했고, 화자가 XRP와 헤어질 결심을 표명",
    "date": "2026-02-18",
    "ts": "0:01",
    "url": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "videoUrl": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "speaker": "코린이 아빠",
    "video_id": "7AaksU-R3dg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "월드리버티파이낸셜",
    "dirType": "positive",
    "headline": "월드 리버티 파이낸셜이 토큰이 있거든요. 토큰 상장돼 있는데 20% 정도가 올랐습니다. 하...",
    "quote": "월드 리버티 파이낸셜이 토큰이 있거든요. 토큰 상장돼 있는데 20% 정도가 올랐습니다. 하루 만에",
    "detail": "마라라고 포럼 개최 후 WLFI 토큰이 하루 만에 20% 상승했다는 사실 전달과 함께 긍정적 언급",
    "date": "2026-02-18",
    "ts": "1:08",
    "url": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "videoUrl": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "speaker": "코린이 아빠",
    "video_id": "7AaksU-R3dg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "알트코인",
    "dirType": "strong_sell",
    "headline": "2026년 알트코인 제가 대멸종할 거라고 이제 얘기를 했었잖아요. 대부분의 코인들이 다 지...",
    "quote": "2026년 알트코인 제가 대멸종할 거라고 이제 얘기를 했었잖아요. 대부분의 코인들이 다 지금 멸종 단계로 가고 있죠. 계속 떨어지죠",
    "detail": "화자가 예측한 2026년 알트코인 대멸종이 현실화되고 있다며 강력한 부정적 전망 표명",
    "date": "2026-02-18",
    "ts": "5:22",
    "url": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "videoUrl": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "speaker": "코린이 아빠",
    "video_id": "7AaksU-R3dg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "sell",
    "headline": "수틀리면 제가 제일 먼저 탈출합니다. 제가 혹시라도 어 이거 뭔가 네러티브 데이터 이거 너...",
    "quote": "수틀리면 제가 제일 먼저 탈출합니다. 제가 혹시라도 어 이거 뭔가 네러티브 데이터 이거 너무 잘못 가고 있는데 하면 제가 여러분들한테 경고도 하고 저부터 먼저 탈출할 겁니다",
    "detail": "화자가 캔톤에 투자하고 있지만, 상황이 나빠지면 본인이 먼저 탈출할 것이라고 명시적으로 언급",
    "date": "2026-02-18",
    "ts": "6:29",
    "url": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "videoUrl": "https://www.youtube.com/watch?v=7AaksU-R3dg",
    "speaker": "코린이 아빠",
    "video_id": "7AaksU-R3dg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "지금 1년에 5억 달러가 넘어가는 매출인데 지금 캔톤 코인의 시가총액은 50억 달러가 안 ...",
    "quote": "지금 1년에 5억 달러가 넘어가는 매출인데 지금 캔톤 코인의 시가총액은 50억 달러가 안 되죠. 그러니 얼마나 밸루에이션이 낮은 겁니까?",
    "detail": "매출 대비 시가총액이 저평가되어 있다는 밸류에이션 분석",
    "date": "2026-01-18",
    "ts": "8:43",
    "url": "https://www.youtube.com/watch?v=82TEaq8GIfc",
    "videoUrl": "https://www.youtube.com/watch?v=82TEaq8GIfc",
    "speaker": "코린이 아빠",
    "video_id": "82TEaq8GIfc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캐톤네트워크",
    "dirType": "positive",
    "headline": "금융 기관에게 RWA는 생존의 기술입니다. 실리콘 밸리 은행이 안 되려면, 캔톤에 들어와서...",
    "quote": "금융 기관에게 RWA는 생존의 기술입니다. 실리콘 밸리 은행이 안 되려면, 캔톤에 들어와서 유동성을 실시간 유동성을 확보할 수 있어야 되겠죠",
    "detail": "SVB 파산 사례를 통해 디지털 뱅크런 시대에 프라이빗 블록체인 기반의 실시간 유동성 확보가 금융기관에게 필수적임을 설명하며, 캔톤 네트워크의 구조적 필요성을 강조",
    "date": "2025-12-26",
    "ts": "13:52",
    "url": "https://www.youtube.com/watch?v=8VIfrqxW4wc",
    "videoUrl": "https://www.youtube.com/watch?v=8VIfrqxW4wc",
    "speaker": "코린이 아빠",
    "video_id": "8VIfrqxW4wc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "브로드리지파이낸셜",
    "dirType": "positive",
    "headline": "브로드리지 파이낸셜이 뭐냐면 레포거래 하는 기관인데 보시면 주식이 상승하는 아주 우량 기업...",
    "quote": "브로드리지 파이낸셜이 뭐냐면 레포거래 하는 기관인데 보시면 주식이 상승하는 아주 우량 기업입니다. 캔톤 네트워크하고 연결이 돼 있어 가지고 여기서 분산 원장 레포거래를 하는데 이게 전년 동기 대비 거의 500%가 폭증했습니다",
    "detail": "캔톤 네트워크와 연결된 브로드리지 파이낸셜의 레포거래 급증(500%)을 통해 실제 비즈니스 성과와 캔톤 생태계 활용도를 설명",
    "date": "2025-12-26",
    "ts": "10:40",
    "url": "https://www.youtube.com/watch?v=8VIfrqxW4wc",
    "videoUrl": "https://www.youtube.com/watch?v=8VIfrqxW4wc",
    "speaker": "코린이 아빠",
    "video_id": "8VIfrqxW4wc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "오직 실적으로 말하는 코인은 오직 하나뿐인 캔톤. 밸류에이션이 여섯 배, 일곱배밖에 안 되...",
    "quote": "오직 실적으로 말하는 코인은 오직 하나뿐인 캔톤. 밸류에이션이 여섯 배, 일곱배밖에 안 되는 알트코인이 어디 있냐고 저는 질문하는 거예요. 이런 말도 안 되는 코인이 어디 있냐고 질문하는 겁니다.",
    "detail": "화자가 2026 알트코인 대멸종을 예견하면서도 캔톤만이 실제 실적(하루 300만 달러 매출)을 보여주는 유일한 생존자라고 극찬. RWA 트렌드에서 실제로 금융 기관과 네트워크가 들어와 실적을 증명하고 있다며 강력 추천",
    "date": "2026-02-04",
    "ts": "10:04",
    "url": "https://www.youtube.com/watch?v=A7qHwvcGh9A",
    "videoUrl": "https://www.youtube.com/watch?v=A7qHwvcGh9A",
    "speaker": "코린이 아빠",
    "video_id": "A7qHwvcGh9A",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이더리움은 희소성의 원리로 돌아갔다. 발행량이 -90% 그래서 토큰의 숫자도 더 이상 생산...",
    "quote": "이더리움은 희소성의 원리로 돌아갔다. 발행량이 -90% 그래서 토큰의 숫자도 더 이상 생산하지 않아요. 연간 인플레이션 비율이 예전 4.5%에서 0.5% 미만으로 엄청나게 줄어들었다.",
    "detail": "이더리움의 구조적 변화로 인한 희소성 증가를 긍정적으로 평가",
    "date": "2025-11-16",
    "ts": "5:25",
    "url": "https://www.youtube.com/watch?v=BVUT2DMnZlg",
    "videoUrl": "https://www.youtube.com/watch?v=BVUT2DMnZlg",
    "speaker": "코린이 아빠",
    "video_id": "BVUT2DMnZlg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "buy",
    "headline": "비트마인부터 먼저 담고 시작을 해라. 비트마인 담아야죠, 빨리.",
    "quote": "비트마인부터 먼저 담고 시작을 해라. 비트마인 담아야죠, 빨리.",
    "detail": "국민연금이 비트마인을 담지 않는 상황을 비판하며, 국민연금이 비트마인에 투자해야 한다고 강력히 주장",
    "date": "2025-08-20",
    "ts": "6:00",
    "url": "https://www.youtube.com/watch?v=CutCWEEnuEU",
    "videoUrl": "https://www.youtube.com/watch?v=CutCWEEnuEU",
    "speaker": "코린이 아빠",
    "video_id": "CutCWEEnuEU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "1국민 1 이더리움 각기 운동할 겁니다. 1인 1 이더륨 여러분 이거 600만 원이에요. ...",
    "quote": "1국민 1 이더리움 각기 운동할 겁니다. 1인 1 이더륨 여러분 이거 600만 원이에요. 충분히 사실 수 있습니다.",
    "detail": "'1국민 1이더리움' 캠페인을 통해 모든 국민이 이더리움을 보유해야 한다고 주장하며, 600만원으로 구매 가능하다고 언급",
    "date": "2025-08-20",
    "ts": "6:14",
    "url": "https://www.youtube.com/watch?v=CutCWEEnuEU",
    "videoUrl": "https://www.youtube.com/watch?v=CutCWEEnuEU",
    "speaker": "코린이 아빠",
    "video_id": "CutCWEEnuEU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "concern",
    "headline": "비트코인은 이미 달러에 종속되었다. 미국 국채 시장에 종속 변수가 된게 아닌가라는 의심을 ...",
    "quote": "비트코인은 이미 달러에 종속되었다. 미국 국채 시장에 종속 변수가 된게 아닌가라는 의심을 하고 있어요. 미국 장기채 금리가 상승하면 비트코인은 하락 압력을 받을 수밖에 없습니다.",
    "detail": "글로벌 M2와 비트코인의 상관관계가 깨졌다고 주장. 2025년 들어 상관계수가 0.36까지 떨어졌으며, 비트코인이 미국 자산화되고 기관 중심으로 움직이면서 달러에 종속되었다는 분석",
    "date": "2025-11-07",
    "ts": "9:10",
    "url": "https://www.youtube.com/watch?v=DwAUo9LmoSo",
    "videoUrl": "https://www.youtube.com/watch?v=DwAUo9LmoSo",
    "speaker": "코린이 아빠",
    "video_id": "DwAUo9LmoSo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "다음 시간에는 이더리움 투자에 대한 박해가 시작되었다라는 주제를 가지고 또 얘기 드려 보도...",
    "quote": "다음 시간에는 이더리움 투자에 대한 박해가 시작되었다라는 주제를 가지고 또 얘기 드려 보도록 하겠습니다.",
    "detail": "다음 영상 예고로 언급된 내용으로, 이더리움에 대한 부정적 전망을 시사",
    "date": "2025-11-07",
    "ts": "9:36",
    "url": "https://www.youtube.com/watch?v=DwAUo9LmoSo",
    "videoUrl": "https://www.youtube.com/watch?v=DwAUo9LmoSo",
    "speaker": "코린이 아빠",
    "video_id": "DwAUo9LmoSo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "concern",
    "headline": "스위프트를 대체하겠다는 XRP의 계획은 과연 정말로 그렇게 될까요? 여러분도 한번 생각을 ...",
    "quote": "스위프트를 대체하겠다는 XRP의 계획은 과연 정말로 그렇게 될까요? 여러분도 한번 생각을 해 보세요.",
    "detail": "XRP의 핵심 네러티브인 스위프트 대체에 대해 의문을 제기하며 투자자들에게 재고를 요구",
    "date": "2025-07-27",
    "ts": "2:03",
    "url": "https://www.youtube.com/watch?v=E4uoauB1dyM",
    "videoUrl": "https://www.youtube.com/watch?v=E4uoauB1dyM",
    "speaker": "코린이 아빠",
    "video_id": "E4uoauB1dyM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "strong_buy",
    "headline": "저는이 가운데 이더륨이 바로 피터이 생각하는 개인이 통제하는 디지털 화폐의 중심이라고 생각...",
    "quote": "저는이 가운데 이더륨이 바로 피터이 생각하는 개인이 통제하는 디지털 화폐의 중심이라고 생각해서 BMR에 과감하게 배팅을 했습니다",
    "detail": "화자가 피터 틸의 페이팔 마피아 철학과 이더리움 생태계를 연결하여 BMNR에 대한 강한 확신을 표현하며 본인이 실제로 투자했다고 밝힘",
    "date": "2025-07-31",
    "ts": "9:07",
    "url": "https://www.youtube.com/watch?v=G1Nl97SgGJY",
    "videoUrl": "https://www.youtube.com/watch?v=G1Nl97SgGJY",
    "speaker": "코린이 아빠",
    "video_id": "G1Nl97SgGJY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "제가 검토하고 또 검토했죠. 네. 거의 열흘 동안 제가 검토를 했거든요. 자, 상장되자마자...",
    "quote": "제가 검토하고 또 검토했죠. 네. 거의 열흘 동안 제가 검토를 했거든요. 자, 상장되자마자 52건이거든요. 네. 그래서 캔톤 코인",
    "detail": "화자가 열흘간 검증 후 직접 투자한 종목. 바이낸스 선물 상장, 아크 인베스트먼트 투자 등을 근거로 제시하며 스캠 의혹에 반박",
    "date": "2025-12-03",
    "ts": "1:27",
    "url": "https://www.youtube.com/watch?v=GHTrpr3AOhY",
    "videoUrl": "https://www.youtube.com/watch?v=GHTrpr3AOhY",
    "speaker": "코린이 아빠",
    "video_id": "GHTrpr3AOhY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "이더리움을 올라가기만 하면 이건 정말 빠르게 올라갈 겁니다",
    "quote": "이더리움을 올라가기만 하면 이건 정말 빠르게 올라갈 겁니다",
    "detail": "비트마인의 공격적 매집 전략으로 인해 이더리움 상승 시 빠른 주가 상승 예상",
    "date": "2025-07-25",
    "ts": "5:12",
    "url": "https://www.youtube.com/watch?v=H2OP8hKs-Tk",
    "videoUrl": "https://www.youtube.com/watch?v=H2OP8hKs-Tk",
    "speaker": "코린이 아빠",
    "video_id": "H2OP8hKs-Tk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "아직 기관들이 다 담지 못했다. 네. 다 담지 않았죠. 어, 아직 매집하려면 아직 멀었습니...",
    "quote": "아직 기관들이 다 담지 못했다. 네. 다 담지 않았죠. 어, 아직 매집하려면 아직 멀었습니다",
    "detail": "이더리움이 현재 횡보하는 이유를 기관 매집 미완료로 설명하며, 향후 상승 가능성을 시사",
    "date": "2025-07-25",
    "ts": "0:50",
    "url": "https://www.youtube.com/watch?v=H2OP8hKs-Tk",
    "videoUrl": "https://www.youtube.com/watch?v=H2OP8hKs-Tk",
    "speaker": "코린이 아빠",
    "video_id": "H2OP8hKs-Tk",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "비트마인은 정말 또 다른 템버거가 될 수 있을까?... 이런 은행이 비트마인을 나중에 되게...",
    "quote": "비트마인은 정말 또 다른 템버거가 될 수 있을까?... 이런 은행이 비트마인을 나중에 되게 사고 싶겠죠. 그래서 템보의 꿈 한번 꺼 봅니다",
    "detail": "비트마인의 시총이 미국 대형 은행들 대비 100-200배 작아서 인수 대상이 될 수 있고 텐배거 가능성을 언급",
    "date": "2025-07-22",
    "ts": "1:59",
    "url": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "videoUrl": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "speaker": "코린이 아빠",
    "video_id": "HIdHdpfBwmA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "체인링크",
    "dirType": "buy",
    "headline": "저도 어제 어, 비트마인이 안 사져 가지고 남는 돈으로 샤프링크를 좀 샀어요. 왜냐면 3일...",
    "quote": "저도 어제 어, 비트마인이 안 사져 가지고 남는 돈으로 샤프링크를 좀 샀어요. 왜냐면 3일 연속 떨어졌거든요",
    "detail": "화자가 3일 연속 하락한 체인링크를 단기 차익실현 목적으로 매수했다고 언급",
    "date": "2025-07-22",
    "ts": "3:13",
    "url": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "videoUrl": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "speaker": "코린이 아빠",
    "video_id": "HIdHdpfBwmA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이더륨이 가면 자, 둘 다 상승을 하겠죠... 이더륨에 대한 공부를 확실하게 할 필요가 있...",
    "quote": "이더륨이 가면 자, 둘 다 상승을 하겠죠... 이더륨에 대한 공부를 확실하게 할 필요가 있습니다. 왜 이더륨을 기관이나 지금 미국에서 되게 주목하고 있는지 아셔야 되고",
    "detail": "이더리움 상승 시 체인링크와 비트마인도 함께 오를 것이며, 미국 기관들이 이더리움에 주목하고 있다고 설명",
    "date": "2025-07-22",
    "ts": "2:49",
    "url": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "videoUrl": "https://www.youtube.com/watch?v=HIdHdpfBwmA",
    "speaker": "코린이 아빠",
    "video_id": "HIdHdpfBwmA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "아직 저는 멀었다고 생각을 합니다. 그래서 실제로 연세가 좀 있으신 분들 아니면은 이제 좀...",
    "quote": "아직 저는 멀었다고 생각을 합니다. 그래서 실제로 연세가 좀 있으신 분들 아니면은 이제 좀 돈이 있는 자산가분들, 좀 보수적인 분들 이런 분들은 네. 이도움 뭐 비트도 안 하는데 이도 하겠습니까?",
    "detail": "FOMO(공포 심리)가 아직 오지 않았다고 판단하며, 보수적인 투자자들이 아직 진입하지 않은 상황을 이더리움의 상승 여력이 남아있다는 긍정적 신호로 해석",
    "date": "2025-09-10",
    "ts": "4:42",
    "url": "https://www.youtube.com/watch?v=Je_JJcSzctY",
    "videoUrl": "https://www.youtube.com/watch?v=Je_JJcSzctY",
    "speaker": "코린이 아빠",
    "video_id": "Je_JJcSzctY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "저는 이게 저평가라고 생각을 하는 거죠",
    "quote": "저는 이게 저평가라고 생각을 하는 거죠",
    "detail": "PSR 기준 13.86배로 캔톤의 가치를 평가하면서 저평가라고 판단",
    "date": "2026-01-04",
    "ts": "12:44",
    "url": "https://www.youtube.com/watch?v=NeL2M9UvF24",
    "videoUrl": "https://www.youtube.com/watch?v=NeL2M9UvF24",
    "speaker": "코린이 아빠",
    "video_id": "NeL2M9UvF24",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "concern",
    "headline": "당장에 뭐 다음 달에 다다음 달에 올라갈 것도 아닌데 이걸 왜 투자해야 되냐 이렇게 생각하...",
    "quote": "당장에 뭐 다음 달에 다다음 달에 올라갈 것도 아닌데 이걸 왜 투자해야 되냐 이렇게 생각하시는게 당연한 겁니다",
    "detail": "CC코인의 단기적 상승 가능성이 낮다고 언급하며 단기 투자에 대한 회의적 시각을 표현",
    "date": "2025-12-04",
    "ts": "2:38",
    "url": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "videoUrl": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "speaker": "코린이 아빠",
    "video_id": "OLdoaHelitU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "buy",
    "headline": "저는이 그래서 비트마인하고 이더한테 몰빵을 한 거예요",
    "quote": "저는이 그래서 비트마인하고 이더한테 몰빵을 한 거예요",
    "detail": "화자가 비트코인과 이더리움에 집중 투자했다고 언급하며 강한 신뢰를 표현",
    "date": "2025-12-04",
    "ts": "7:11",
    "url": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "videoUrl": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "speaker": "코린이 아빠",
    "video_id": "OLdoaHelitU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "저는이 그래서 비트마인하고 이더한테 몰빵을 한 거예요",
    "quote": "저는이 그래서 비트마인하고 이더한테 몰빵을 한 거예요",
    "detail": "화자가 비트코인과 이더리움에 집중 투자했다고 언급하며 강한 신뢰를 표현",
    "date": "2025-12-04",
    "ts": "7:11",
    "url": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "videoUrl": "https://www.youtube.com/watch?v=OLdoaHelitU",
    "speaker": "코린이 아빠",
    "video_id": "OLdoaHelitU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "CC코인 대신에 TH을 사도 될까요라는 질문을 하시는 거예요. 네. 당연히 여러분들은 CC...",
    "quote": "CC코인 대신에 TH을 사도 될까요라는 질문을 하시는 거예요. 네. 당연히 여러분들은 CC코인 사기 어려우실 거예요. 그래서 TH라 사는 건 당연히 되죠.",
    "detail": "CC코인을 직접 사기 어려운 개인투자자들에게 THAR을 통한 우회 투자를 추천",
    "date": "2025-12-19",
    "ts": "3:07",
    "url": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "videoUrl": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "speaker": "코린이 아빠",
    "video_id": "OOL77dtnR3g",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "타르",
    "dirType": "buy",
    "headline": "THAR은 왜 개미에게 최고의 선택지일까라는 설명을 드릴게요. TH한테 우리가 투자를 하면...",
    "quote": "THAR은 왜 개미에게 최고의 선택지일까라는 설명을 드릴게요. TH한테 우리가 투자를 하면 얘네들은 켄톤 네트워크에서 슈퍼 밸리데이터 중 슈퍼 밸리입니다.",
    "detail": "개인이 접근하기 어려운 CC코인 스테이킹 수익을 THAR을 통해 간접 투자할 수 있다고 설명",
    "date": "2025-12-19",
    "ts": "15:27",
    "url": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "videoUrl": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "speaker": "코린이 아빠",
    "video_id": "OOL77dtnR3g",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "서클",
    "dirType": "positive",
    "headline": "서클이 노드로 들어와 있습니다. USDC를 메인 스테이블 코인으로 쓸 가능성이 대단히 높다...",
    "quote": "서클이 노드로 들어와 있습니다. USDC를 메인 스테이블 코인으로 쓸 가능성이 대단히 높다. 그래서 서클도 굉장히 전망이 나쁘지 않다라는 생각이 들었습니다.",
    "detail": "캔톤 네트워크에서 USDC가 주요 스테이블코인으로 채택될 가능성이 높다는 분석",
    "date": "2025-12-19",
    "ts": "21:03",
    "url": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "videoUrl": "https://www.youtube.com/watch?v=OOL77dtnR3g",
    "speaker": "코린이 아빠",
    "video_id": "OOL77dtnR3g",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "리테일 시장 확장을 위한 준비를 지금까지 저는 차곡차곡 해오고 있다고 생각을 해요. 켄톤 ...",
    "quote": "리테일 시장 확장을 위한 준비를 지금까지 저는 차곡차곡 해오고 있다고 생각을 해요. 켄톤 네트워크가 단지문 대형 기관들끼리의 거래다. 네 절대 그렇지 않다는 거예요.",
    "detail": "화자는 캔톤이 기관 전용이라는 시각을 강하게 반박하며, 한화증권-크리소스 연결, 삼성월렛 연동 등 리테일 확장을 위한 구체적 준비사항들을 제시하며 긍정적 전망을 표현",
    "date": "2026-01-27",
    "ts": "3:53",
    "url": "https://www.youtube.com/watch?v=PGQW7nyoRRI",
    "videoUrl": "https://www.youtube.com/watch?v=PGQW7nyoRRI",
    "speaker": "코린이 아빠",
    "video_id": "PGQW7nyoRRI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "캔톤 네트워크는 댐어를 통해서 A 기관과 B 기관간의 거래가 디지털 방식으로 원자적으로 거...",
    "quote": "캔톤 네트워크는 댐어를 통해서 A 기관과 B 기관간의 거래가 디지털 방식으로 원자적으로 거래되는 거래의 종결성을 갖고 있습니다. 그렇기 때문에 알고리즘 자동화에 최적화되어 있는 거래 네트워크라고 할 수가 있어요",
    "detail": "월가에서 자동화 거래로 전환되는 트렌드에 맞춰 캔톤이 최적화된 시스템이라는 분석",
    "date": "2026-01-20",
    "ts": "4:13",
    "url": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "videoUrl": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "speaker": "코린이 아빠",
    "video_id": "Pb_RkyKhOcM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "neutral",
    "headline": "비트코인 처음에 다 사기라고 했잖아요. 근데 지금 와서 어떻습니까? 지금 거의 뭐 1억이 ...",
    "quote": "비트코인 처음에 다 사기라고 했잖아요. 근데 지금 와서 어떻습니까? 지금 거의 뭐 1억이 넘잖아요. 그래서 이분들은 이미 네. 다 그 영광에 대한 보상을 받아 갔습니다",
    "detail": "과거의 영광에 대한 키워드를 설명하면서 비트코인이 이미 충분한 수익을 제공했다는 사실 언급으로, 현재 시점에서의 투자 의견은 아님",
    "date": "2026-01-20",
    "ts": "9:47",
    "url": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "videoUrl": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "speaker": "코린이 아빠",
    "video_id": "Pb_RkyKhOcM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "neutral",
    "headline": "이더리움도 마찬가지죠. 옛날에 얼마였습니까? 막 300원, 500원 뭐 이랬거든요. 근데 ...",
    "quote": "이더리움도 마찬가지죠. 옛날에 얼마였습니까? 막 300원, 500원 뭐 이랬거든요. 근데 지금 얼마예요? 거의 뭐 400만 원, 500만 원 왔다 갔다 하잖아요",
    "detail": "과거의 성과에 대한 언급으로, 현재 시점에서의 투자 의견이 아닌 역사적 사실 설명",
    "date": "2026-01-20",
    "ts": "9:55",
    "url": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "videoUrl": "https://www.youtube.com/watch?v=Pb_RkyKhOcM",
    "speaker": "코린이 아빠",
    "video_id": "Pb_RkyKhOcM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "캔톤 네트워크는 독자 기술, 네트워크 효과, 규모의 경제, 그리고 브랜드 전략... 굉장히...",
    "quote": "캔톤 네트워크는 독자 기술, 네트워크 효과, 규모의 경제, 그리고 브랜드 전략... 굉장히 빠르고 굉장히 효율적이고 굉장히 안정적인 그런 독자적인 기술성을 가지고 있다",
    "detail": "피터 틸의 독점 기업 4대 요소를 캔톤 네트워크에 적용하여 분석하며, 독자적 기술력과 경쟁 우위를 강조",
    "date": "2025-12-11",
    "ts": "6:25",
    "url": "https://www.youtube.com/watch?v=Quyl_Xss93E",
    "videoUrl": "https://www.youtube.com/watch?v=Quyl_Xss93E",
    "speaker": "코린이 아빠",
    "video_id": "Quyl_Xss93E",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "이더리움의 지위는 과연 독점적일까?... 과연 이더리움이 비트코인의 장벽을 넘을 수 있을까...",
    "quote": "이더리움의 지위는 과연 독점적일까?... 과연 이더리움이 비트코인의 장벽을 넘을 수 있을까요?... 아직까지 제대로 터진 적이 없었다. 이게 냉정한 현실입니다",
    "detail": "이더리움의 독점적 지위와 성장 가능성에 대해 의문을 제기하며, 킬러앱 부재와 실제 사용률 저조를 지적",
    "date": "2025-12-11",
    "ts": "1:15",
    "url": "https://www.youtube.com/watch?v=Quyl_Xss93E",
    "videoUrl": "https://www.youtube.com/watch?v=Quyl_Xss93E",
    "speaker": "코린이 아빠",
    "video_id": "Quyl_Xss93E",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "기관들은 블록체인의 해계모니를 원합니다. 그들은 CC코인의 당장의 가격이 뭐 이게 두 배가...",
    "quote": "기관들은 블록체인의 해계모니를 원합니다. 그들은 CC코인의 당장의 가격이 뭐 이게 두 배가고 300하고 관심이 없습니다. 골드만 삭스가 그걸 위해서 이걸 했겠습니까? 마이크로소프트하고 지금 딜로이트하고 전부 노드르에 참여를 하고 있거든요.",
    "detail": "화자는 CC코인이 11월 공포 구간에 상장한 이유를 분석하면서, 기관들이 단순한 가격 차익이 아닌 RWA 시장의 헤게모니를 위해 참여하고 있다고 설명. 골드만 삭스, 마이크로소프트, 딜로이트 등 대형 기관들의 노드 참여를 언급하며 장기적 가치를 시사",
    "date": "2025-12-03",
    "ts": "4:58",
    "url": "https://www.youtube.com/watch?v=Qwdgrkfs-hE",
    "videoUrl": "https://www.youtube.com/watch?v=Qwdgrkfs-hE",
    "speaker": "코린이 아빠",
    "video_id": "Qwdgrkfs-hE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "concern",
    "headline": "다른 나라들이 비트코인을 지정학적으로 미국의 자산으로 보고 있는 거죠. 미국의 편입된 미국...",
    "quote": "다른 나라들이 비트코인을 지정학적으로 미국의 자산으로 보고 있는 거죠. 미국의 편입된 미국이 통제하는 자산으로 보는 거예요. 그냥 달러에 봉사하는 슬레이브 네. 달러 슬레이브 코인이다라고 저는 생각을 합니다.",
    "detail": "비트코인이 중립성을 잃고 미국 달러 패권에 종속된 자산이 되었다는 분석",
    "date": "2026-01-12",
    "ts": "6:01",
    "url": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "videoUrl": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "speaker": "코린이 아빠",
    "video_id": "RIhGc56eSHo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "솔라나",
    "dirType": "positive",
    "headline": "특히나 저는 좀 솔라나에 좀 주목을 해요. 근데 솔라나는 앞으로 좀 더 괜찮지 않을까? 여...",
    "quote": "특히나 저는 좀 솔라나에 좀 주목을 해요. 근데 솔라나는 앞으로 좀 더 괜찮지 않을까? 여기는 소각량도 괜찮고 지금 밸루에이션도 이더류에 비해서 훨씬 낮은 편이죠. 솔라나 괜찮다라고 저 보고 있고",
    "detail": "생존 가능한 알트코인 중 하나로 솔라나를 언급하며, 소각량과 저평가 상태를 긍정적 요인으로 제시",
    "date": "2026-01-12",
    "ts": "9:24",
    "url": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "videoUrl": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "speaker": "코린이 아빠",
    "video_id": "RIhGc56eSHo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "리플",
    "dirType": "sell",
    "headline": "저는 리플은 사라질 코인이라고 저는 생각을 하죠. 아무리 리플 맥시들이 공격을 해도 저는 ...",
    "quote": "저는 리플은 사라질 코인이라고 저는 생각을 하죠. 아무리 리플 맥시들이 공격을 해도 저는 이 뷰에는 변함이 없습니다. 리플은 결국에는 민코인이다라고 저는 생각을 합니다.",
    "detail": "생존 가능한 코인 목록에서 리플을 제외하며, 민코인(사기코인)으로 분류하는 강한 부정적 견해",
    "date": "2026-01-12",
    "ts": "9:39",
    "url": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "videoUrl": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "speaker": "코린이 아빠",
    "video_id": "RIhGc56eSHo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "저는 켄토니야말로 RW를 통해서 미국과 월스트리트의 이익을 극대화시킬 진정한 지정학적 자산...",
    "quote": "저는 켄토니야말로 RW를 통해서 미국과 월스트리트의 이익을 극대화시킬 진정한 지정학적 자산이라고 저는 생각을 합니다. 결국 달러 스테이블 코인 그다음에 달러 국채 이런 것들을 통해서 전 세계 금융을 디지털로 전환시키고 그 디지털의 중심이 다시 달러가 되는 그게 바로 켄톤노의 전략과 미국의 전략이 맞아 있는 거죠.",
    "detail": "영상 제목에서 언급한 '현실적인' 투자 대안으로 캔톤을 제시하며, 실질적 매출과 미국 디지털 달러 패권 전략에 부합하는 자산으로 평가",
    "date": "2026-01-12",
    "ts": "11:06",
    "url": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "videoUrl": "https://www.youtube.com/watch?v=RIhGc56eSHo",
    "speaker": "코린이 아빠",
    "video_id": "RIhGc56eSHo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "엔비디아",
    "dirType": "concern",
    "headline": "엔비디아의 단독 질주가 언제까지 계속될 건지 의문스러운 거죠",
    "quote": "엔비디아의 단독 질주가 언제까지 계속될 건지 의문스러운 거죠",
    "detail": "마이클 버리의 공매도, 손정의의 완전 매각, 그리고 AI 응용 시대로의 전환에 따른 우려 표명",
    "date": "2025-11-12",
    "ts": "6:34",
    "url": "https://www.youtube.com/watch?v=RabsURttGlI",
    "videoUrl": "https://www.youtube.com/watch?v=RabsURttGlI",
    "speaker": "코린이 아빠",
    "video_id": "RabsURttGlI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "팔란티어",
    "dirType": "concern",
    "headline": "팔란테어의 주가가 하락할 것이다",
    "quote": "팔란테어의 주가가 하락할 것이다",
    "detail": "마이클 버리가 10억 달러 이상 숏 배팅하며 AI 산업 붕괴를 예측한다는 내용 전달",
    "date": "2025-11-12",
    "ts": "0:34",
    "url": "https://www.youtube.com/watch?v=RabsURttGlI",
    "videoUrl": "https://www.youtube.com/watch?v=RabsURttGlI",
    "speaker": "코린이 아빠",
    "video_id": "RabsURttGlI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "오라클",
    "dirType": "concern",
    "headline": "오라클은 부채 비율이 굉장히 높더라고요. 거의 400%가 넘어요. 과대 평가할 가능성이 대...",
    "quote": "오라클은 부채 비율이 굉장히 높더라고요. 거의 400%가 넘어요. 과대 평가할 가능성이 대단히 높고",
    "detail": "데이터센터 과투자와 감가상각 문제로 인한 실적 부풀리기 우려",
    "date": "2025-11-12",
    "ts": "2:05",
    "url": "https://www.youtube.com/watch?v=RabsURttGlI",
    "videoUrl": "https://www.youtube.com/watch?v=RabsURttGlI",
    "speaker": "코린이 아빠",
    "video_id": "RabsURttGlI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "메타",
    "dirType": "concern",
    "headline": "메타도 수익이 높다고는 하지만 이거 역시 과대 평가돼 있다",
    "quote": "메타도 수익이 높다고는 하지만 이거 역시 과대 평가돼 있다",
    "detail": "AI 관련 기업들의 실적 부풀리기 우려의 일환으로 메타도 과대평가되었다는 판단",
    "date": "2025-11-12",
    "ts": "2:21",
    "url": "https://www.youtube.com/watch?v=RabsURttGlI",
    "videoUrl": "https://www.youtube.com/watch?v=RabsURttGlI",
    "speaker": "코린이 아빠",
    "video_id": "RabsURttGlI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "1국민 1 이더룡 꼭 사셔야죠",
    "quote": "1국민 1 이더룡 꼭 사셔야죠",
    "detail": "노동의 종말과 투자 필수 시대에 대한 결론으로 이더리움 매수 권유",
    "date": "2025-11-12",
    "ts": "9:50",
    "url": "https://www.youtube.com/watch?v=RabsURttGlI",
    "videoUrl": "https://www.youtube.com/watch?v=RabsURttGlI",
    "speaker": "코린이 아빠",
    "video_id": "RabsURttGlI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "BMNR이 옥토 투자를 통해서 스스로 MSTR가 어떻게 다른지에 대해서 직접 증명해 보였다...",
    "quote": "BMNR이 옥토 투자를 통해서 스스로 MSTR가 어떻게 다른지에 대해서 직접 증명해 보였다. 단순한 이더리움 매집 회사가 아니라 앞으로 이더리움 생태계에서 정말 은행과 같은 투자 운용사 같은 그런 형 큰 형님 역할을 할 것이다라고 저는 생각을 합니다.",
    "detail": "비트마인의 옥토 투자를 통해 단순 매집 회사가 아닌 생태계 리더로서의 역할을 긍정적으로 평가",
    "date": "2025-09-14",
    "ts": "9:25",
    "url": "https://www.youtube.com/watch?v=SscZvgQJDfA",
    "videoUrl": "https://www.youtube.com/watch?v=SscZvgQJDfA",
    "speaker": "코린이 아빠",
    "video_id": "SscZvgQJDfA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "월드코인",
    "dirType": "buy",
    "headline": "저는 어 토요일 날네 어제죠. 어제 아비트럼하고 솔라나 마진 포지션의 수입금으로 저는 조금...",
    "quote": "저는 어 토요일 날네 어제죠. 어제 아비트럼하고 솔라나 마진 포지션의 수입금으로 저는 조금 담았어요. 월드코인 지금 한 2,500달러 정도 투자했습니다.",
    "detail": "화자가 직접 월드코인을 2,500달러 투자했다고 밝힘",
    "date": "2025-09-14",
    "ts": "7:23",
    "url": "https://www.youtube.com/watch?v=SscZvgQJDfA",
    "videoUrl": "https://www.youtube.com/watch?v=SscZvgQJDfA",
    "speaker": "코린이 아빠",
    "video_id": "SscZvgQJDfA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "서클",
    "dirType": "sell",
    "headline": "서클이 올랐을 때 10 몇 % 올랐었거든요. 엊그제. 그래서 그때 예, 팔았죠",
    "quote": "서클이 올랐을 때 10 몇 % 올랐었거든요. 엊그제. 그래서 그때 예, 팔았죠",
    "detail": "화자가 서클을 매수 후 10여% 상승했을 때 익절했다고 설명",
    "date": "2025-09-16",
    "ts": "3:12",
    "url": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "videoUrl": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "speaker": "코린이 아빠",
    "video_id": "T_5EaLRwm8o",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "블리시",
    "dirType": "sell",
    "headline": "과감하게 네. 손 그냥 손실 처리를 해 버렸습니다",
    "quote": "과감하게 네. 손 그냥 손실 처리를 해 버렸습니다",
    "detail": "화자가 97달러에 매수한 블리시가 크게 하락하자 세금 문제로 손실 처리했다고 언급",
    "date": "2025-09-16",
    "ts": "1:59",
    "url": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "videoUrl": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "speaker": "코린이 아빠",
    "video_id": "T_5EaLRwm8o",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "hold",
    "headline": "이더리움이 만 달러 2만 달러 가면 안 팔 자신 있으세요? 예. 익절 안 할 자신 있으세요...",
    "quote": "이더리움이 만 달러 2만 달러 가면 안 팔 자신 있으세요? 예. 익절 안 할 자신 있으세요?",
    "detail": "화자가 이더리움의 장기적 상승 가능성을 언급하며 열정을 가지고 장기 보유해야 한다고 강조",
    "date": "2025-09-16",
    "ts": "5:42",
    "url": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "videoUrl": "https://www.youtube.com/watch?v=T_5EaLRwm8o",
    "speaker": "코린이 아빠",
    "video_id": "T_5EaLRwm8o",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "전 세계 금융망의 온체인 연결은 지금도 가속화되고 있습니다. 캔톤네트워크하고 지금 연결된 ...",
    "quote": "전 세계 금융망의 온체인 연결은 지금도 가속화되고 있습니다. 캔톤네트워크하고 지금 연결된 550개의 벨리데이터가 있습니다. 캔톤 네트워크의 시계는 365일 24시간 멈출 수가 없습니다.",
    "detail": "클래리티 법안 연기와 관계없이 캔톤의 금융 네트워크 확장이 지속되고 있다는 긍정적 전망을 제시하며, JPM코인, 런던증권거래소 등 글로벌 금융기관들과의 연결 확산 사례를 근거로 제시",
    "date": "2026-01-17",
    "ts": "10:08",
    "url": "https://www.youtube.com/watch?v=TjKVuAGhC1M",
    "videoUrl": "https://www.youtube.com/watch?v=TjKVuAGhC1M",
    "speaker": "코린이 아빠",
    "video_id": "TjKVuAGhC1M",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "스테이블코인",
    "dirType": "concern",
    "headline": "거래소는 은행처럼 원금을 보장하지 않죠. 절대 보장하지 않습니다. 만약에 바이낸스가 파산되...",
    "quote": "거래소는 은행처럼 원금을 보장하지 않죠. 절대 보장하지 않습니다. 만약에 바이낸스가 파산되면 어떡할 겁니까? 그러면 수많은 사람들이 예금을 다 날리겠죠.",
    "detail": "스테이블코인 이자 서비스의 리스크를 경고하면서, 거래소 파산 시 예금자 보호가 되지 않는 구조적 문제점을 지적",
    "date": "2026-01-17",
    "ts": "3:08",
    "url": "https://www.youtube.com/watch?v=TjKVuAGhC1M",
    "videoUrl": "https://www.youtube.com/watch?v=TjKVuAGhC1M",
    "speaker": "코린이 아빠",
    "video_id": "TjKVuAGhC1M",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "그래서 야, 뭐 사야 돼? 그럼 어 캔톤사 이렇게 얘기하시면 돼요.",
    "quote": "그래서 야, 뭐 사야 돼? 그럼 어 캔톤사 이렇게 얘기하시면 돼요.",
    "detail": "CC의 정확한 발음을 캔톤이라고 설명하면서, 마지막에 '캔톤 사라'는 매수 권유를 함",
    "date": "2026-02-18",
    "ts": "3:16",
    "url": "https://www.youtube.com/watch?v=ULXCspCxaSg",
    "videoUrl": "https://www.youtube.com/watch?v=ULXCspCxaSg",
    "speaker": "코린이 아빠",
    "video_id": "ULXCspCxaSg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "AI 버블이 계속되든 붕괴하든 캔톤 네트워크의 그 크립토 금융과 RW는 가속화될 수밖에 없...",
    "quote": "AI 버블이 계속되든 붕괴하든 캔톤 네트워크의 그 크립토 금융과 RW는 가속화될 수밖에 없다라고 저는 생각을 합니다",
    "detail": "AI 버블 붕괴 시나리오에서도 캔톤의 디지털 뱅크런 대응 시스템과 자산 토큰화 기능이 핵심 역할을 할 것이라는 강한 확신을 표현. 버블이 지속되든 붕괴하든 상관없이 캔톤의 성장은 필연적이라고 단언",
    "date": "2026-01-23",
    "ts": "10:48",
    "url": "https://www.youtube.com/watch?v=Vy2jrX-uCbY",
    "videoUrl": "https://www.youtube.com/watch?v=Vy2jrX-uCbY",
    "speaker": "코린이 아빠",
    "video_id": "Vy2jrX-uCbY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "진짜 이거는 엄청난 프로젝트예요.",
    "quote": "진짜 이거는 엄청난 프로젝트예요.",
    "detail": "10년간 준비된 프로젝트이며 각국 기관들과 네트워크가 구축되어 있다고 강조하며 매우 긍정적 평가",
    "date": "2025-12-06",
    "ts": "11:48",
    "url": "https://www.youtube.com/watch?v=WmZeNxf7ack",
    "videoUrl": "https://www.youtube.com/watch?v=WmZeNxf7ack",
    "speaker": "코린이 아빠",
    "video_id": "WmZeNxf7ack",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "sell",
    "headline": "롱 포지션부터 일단 다 정리를 했습니다. 네. 그냥 손절 처리해 버렸어요. 네. 그래서 청...",
    "quote": "롱 포지션부터 일단 다 정리를 했습니다. 네. 그냥 손절 처리해 버렸어요. 네. 그래서 청 스스로 청산해 버렸습니다.",
    "detail": "AI 위험성과 청산 공포로 인한 패닉셀로 롱 포지션 전량 정리",
    "date": "2025-11-14",
    "ts": "4:45",
    "url": "https://www.youtube.com/watch?v=X8dT57ap91Q",
    "videoUrl": "https://www.youtube.com/watch?v=X8dT57ap91Q",
    "speaker": "코린이 아빠",
    "video_id": "X8dT57ap91Q",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "sell",
    "headline": "BMR도 여러분 제가 공개해 드렸듯이 전부 다 네. 다 팔았습니다. 네. 다 빨았어요.",
    "quote": "BMR도 여러분 제가 공개해 드렸듯이 전부 다 네. 다 팔았습니다. 네. 다 빨았어요.",
    "detail": "위험 관리 차원에서 레버리지 상품인 비트마인 전량 매도",
    "date": "2025-11-14",
    "ts": "4:59",
    "url": "https://www.youtube.com/watch?v=X8dT57ap91Q",
    "videoUrl": "https://www.youtube.com/watch?v=X8dT57ap91Q",
    "speaker": "코린이 아빠",
    "video_id": "X8dT57ap91Q",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "RWA를 이더리움이 주도하기 어려운 이유... 금융 기관들은 거래 내용이나 포지셔닝이 낱낱...",
    "quote": "RWA를 이더리움이 주도하기 어려운 이유... 금융 기관들은 거래 내용이나 포지셔닝이 낱낱이 공개되는 퍼블릭 블록체인을 싫어합니다. 진짜 싫어해요",
    "detail": "RWA 시장에서 이더리움의 구조적 한계를 지적하며 금융기관들이 퍼블릭 블록체인을 기피한다고 설명",
    "date": "2026-01-02",
    "ts": "8:00",
    "url": "https://www.youtube.com/watch?v=Xhqm11HDPNU",
    "videoUrl": "https://www.youtube.com/watch?v=Xhqm11HDPNU",
    "speaker": "코린이 아빠",
    "video_id": "Xhqm11HDPNU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "캔톤 네트워크가 약 6조 달러입니다. 캔톤이 약 250배가 크죠? 이거 아직 시작도 안 했...",
    "quote": "캔톤 네트워크가 약 6조 달러입니다. 캔톤이 약 250배가 크죠? 이거 아직 시작도 안 했죠?",
    "detail": "이더리움과 캔톤네트워크의 연결 자산 규모를 비교하며 캔톤이 압도적으로 크다는 점을 강조",
    "date": "2026-01-02",
    "ts": "8:50",
    "url": "https://www.youtube.com/watch?v=Xhqm11HDPNU",
    "videoUrl": "https://www.youtube.com/watch?v=Xhqm11HDPNU",
    "speaker": "코린이 아빠",
    "video_id": "Xhqm11HDPNU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "sell",
    "headline": "M2가 증가하면 비트가 따라간다. 분명히 한 달도 전에 친구야, 비트코인 던져라고 영상 만...",
    "quote": "M2가 증가하면 비트가 따라간다. 분명히 한 달도 전에 친구야, 비트코인 던져라고 영상 만들었거든요. M2를 우리가 양으로만 측정을 했는데 결국에는 그게 아니었다. 유동성이라는 건 방향성과 속도 이게 되게 중요한데 변했다. 돈이 다 단데로 다 셌다. 그래서 비트코인 던져라고 얘기했고",
    "detail": "화자가 M2 증가와 비트코인 상관관계에 대한 가설이 틀렸음을 인정하며 매도를 권유한 상황",
    "date": "2026-02-16",
    "ts": "4:51",
    "url": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "videoUrl": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "speaker": "코린이 아빠",
    "video_id": "YxI_Tx5Y-qY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "sell",
    "headline": "이더륨이 울트라사운드 머니가 된다라고 얘기를 했을 때 저는 아, 스테이블 코인이 폭발하면 ...",
    "quote": "이더륨이 울트라사운드 머니가 된다라고 얘기를 했을 때 저는 아, 스테이블 코인이 폭발하면 이더리움이 상승한다. 그건 착각이었다... 그러면서 제가 또 한 달 전에 이더리움도 던져라라고 얘기를 했죠",
    "detail": "화자가 이더리움의 울트라사운드 머니 가설이 틀렸다고 판단하고 매도를 권유한 상황",
    "date": "2026-02-16",
    "ts": "5:43",
    "url": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "videoUrl": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "speaker": "코린이 아빠",
    "video_id": "YxI_Tx5Y-qY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "XRP 빨리 탈출하라고 얘기했죠... 소송 종료가 되면 떡상할 거다. ETF가 승인되면 떡...",
    "quote": "XRP 빨리 탈출하라고 얘기했죠... 소송 종료가 되면 떡상할 거다. ETF가 승인되면 떡상할 거다. 트럼프가 뒷배니까 떡상할 거다. XRP로 미국 국채를 다 갚을 거다... 이거는 신념이 아니라 망상에 가깝다라고 저는 생각을 합니다",
    "detail": "화자가 XRP의 여러 긍정적 내러티브들을 망상이라고 평가하며 탈출을 권유한 상황",
    "date": "2026-02-16",
    "ts": "7:38",
    "url": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "videoUrl": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "speaker": "코린이 아빠",
    "video_id": "YxI_Tx5Y-qY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "그래서 제 친구는 비트코인 다 팔고 XRP 다 팔고네 비트마인 다 팔고 다 저를 따라서 캔...",
    "quote": "그래서 제 친구는 비트코인 다 팔고 XRP 다 팔고네 비트마인 다 팔고 다 저를 따라서 캔톤으로 다 넘어왔죠. 어 그래서 수익률이 나쁘지 않습니다",
    "detail": "화자가 친구와 함께 기존 투자 종목들을 모두 매도하고 캔톤으로 이동했으며, 그 결과 수익률이 좋다고 언급한 상황",
    "date": "2026-02-16",
    "ts": "8:24",
    "url": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "videoUrl": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "speaker": "코린이 아빠",
    "video_id": "YxI_Tx5Y-qY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "sell",
    "headline": "비트 마인도 다 털어내고... 제 친구는 비트코인 다 팔고 XRP 다 팔고네 비트마인 다 ...",
    "quote": "비트 마인도 다 털어내고... 제 친구는 비트코인 다 팔고 XRP 다 팔고네 비트마인 다 팔고 다 저를 따라서 캔톤으로 다 넘어왔죠",
    "detail": "화자가 비트마인을 포함하여 기존 투자 종목들을 모두 매도했다고 언급한 상황",
    "date": "2026-02-16",
    "ts": "6:01",
    "url": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "videoUrl": "https://www.youtube.com/watch?v=YxI_Tx5Y-qY",
    "speaker": "코린이 아빠",
    "video_id": "YxI_Tx5Y-qY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "concern",
    "headline": "절대 함부로 여러분 그 뭐 선물 투자 이거 되게 조심하시고 배율 쓸 때도 굉장히 조심하시고...",
    "quote": "절대 함부로 여러분 그 뭐 선물 투자 이거 되게 조심하시고 배율 쓸 때도 굉장히 조심하시고 그다음에 청산가를 하실 때도 굉장히 보수적으로 접근하실",
    "detail": "레버리지 거래의 위험성과 청산 위험에 대한 강한 경고",
    "date": "2026-01-09",
    "ts": "8:04",
    "url": "https://www.youtube.com/watch?v=YxekoL6IuvM",
    "videoUrl": "https://www.youtube.com/watch?v=YxekoL6IuvM",
    "speaker": "코린이 아빠",
    "video_id": "YxekoL6IuvM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "positive",
    "headline": "XRP 송금용 브릿지 통화에 대한 저는 확신을 합니다. 왜냐 어 올해 2025년도 터 본격...",
    "quote": "XRP 송금용 브릿지 통화에 대한 저는 확신을 합니다. 왜냐 어 올해 2025년도 터 본격적으로 일본의 은행의 80% 다 리플 XRP 사용할 거라고 밝힌 바가 있습니다",
    "detail": "화자가 XRP의 송금 브릿지 통화로서의 역할에 대해 강한 확신을 표현하며, 2025년 일본 은행들의 80%가 XRP를 사용할 계획이라는 구체적인 근거를 제시",
    "date": "2025-04-04",
    "ts": "6:12",
    "url": "https://www.youtube.com/watch?v=ZKi5J5Z7SvE",
    "videoUrl": "https://www.youtube.com/watch?v=ZKi5J5Z7SvE",
    "speaker": "코린이 아빠",
    "video_id": "ZKi5J5Z7SvE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이번 장에 주인공은 이더륨이 될 확률이 대단히 높다고 생각을 합니다.",
    "quote": "이번 장에 주인공은 이더륨이 될 확률이 대단히 높다고 생각을 합니다.",
    "detail": "화자가 이더리움이 현재 사이클의 주인공이 될 가능성이 매우 높다고 명시적으로 전망을 밝힘",
    "date": "2025-07-24",
    "ts": "6:59",
    "url": "https://www.youtube.com/watch?v=a1a52W1UnOU",
    "videoUrl": "https://www.youtube.com/watch?v=a1a52W1UnOU",
    "speaker": "코린이 아빠",
    "video_id": "a1a52W1UnOU",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "concern",
    "headline": "네. 저는 결론부터 말씀드리자면 네, 그렇습니다라고 말씀을 드릴게요. (비트마인에 저는 물...",
    "quote": "네. 저는 결론부터 말씀드리자면 네, 그렇습니다라고 말씀을 드릴게요. (비트마인에 저는 물린 건가요?라는 질문에 대해)",
    "detail": "화자가 비트마인 투자자들이 현재 손실(물림) 상태에 있다고 직접적으로 인정하며, 이더리움 대비 40% 이상 하락한 상황을 설명",
    "date": "2025-09-04",
    "ts": "0:21",
    "url": "https://www.youtube.com/watch?v=aK-QNWiVMdc",
    "videoUrl": "https://www.youtube.com/watch?v=aK-QNWiVMdc",
    "speaker": "코린이 아빠",
    "video_id": "aK-QNWiVMdc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "저는 이더리움을 권유를 드렸죠. 왜냐? 네. 비트마이는 훨씬 어렵습니다... 그래서 저는 ...",
    "quote": "저는 이더리움을 권유를 드렸죠. 왜냐? 네. 비트마이는 훨씬 어렵습니다... 그래서 저는 어 저보다 더 늦게 투자하신 분들, 코인을 잘 모르시는 분들한테는 이더리움을 권내 드리는 거죠",
    "detail": "비트마인 대비 이더리움이 더 안전한 투자처라고 판단하며, 초보 투자자들에게 이더리움을 추천. 화자 본인도 이더리움 포지션 보유 중",
    "date": "2025-09-04",
    "ts": "7:41",
    "url": "https://www.youtube.com/watch?v=aK-QNWiVMdc",
    "videoUrl": "https://www.youtube.com/watch?v=aK-QNWiVMdc",
    "speaker": "코린이 아빠",
    "video_id": "aK-QNWiVMdc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "이 캔톤 캔톤 이거 10달러 갑니다. 10달러. 네. 10달러예요. 앞으로 100배 갑니다...",
    "quote": "이 캔톤 캔톤 이거 10달러 갑니다. 10달러. 네. 10달러예요. 앞으로 100배 갑니다, 여러분. 예, 백하게 설계돼 있어요. 그렇게 설계돼 있습니다. 켄톤이 금융을 다 먹을 거고요. 독점할 거고요. 전 세계 모든 금융을 다 빨아들릴 겁니다.",
    "detail": "화자가 시청자들이 듣고 싶어하는 말의 예시로 제시한 반어적 표현. 바로 뒤에 '기분 좋으시지만 전 절대로 그렇게 얘기 안 하죠'라며 부정",
    "date": "2025-12-31",
    "ts": "1:20",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "알트코인",
    "dirType": "strong_sell",
    "headline": "저는 2026년은 알트코인의 대멸종이 시작될 거라고 말씀드립니다. 알트코인의 대별정이 시작...",
    "quote": "저는 2026년은 알트코인의 대멸종이 시작될 거라고 말씀드립니다. 알트코인의 대별정이 시작될 것이라고.",
    "detail": "화자가 2026년 알트코인 시장 전망에 대한 핵심 메시지. 시장 성숙화에 따라 실적을 묻기 시작할 것이고, 대부분의 알트코인이 사라질 것이라는 주장",
    "date": "2025-12-31",
    "ts": "3:30",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "이더리움도 실적이 나오긴 하지만 시가 총액 대비해서 아직은 많이 부족한 상황이고",
    "quote": "이더리움도 실적이 나오긴 하지만 시가 총액 대비해서 아직은 많이 부족한 상황이고",
    "detail": "이더리움의 실적은 인정하지만 시가총액 대비 충분하지 않다는 우려 표명",
    "date": "2025-12-31",
    "ts": "6:03",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "BNB",
    "dirType": "positive",
    "headline": "BNB가 역시 실적주의죠.",
    "quote": "BNB가 역시 실적주의죠.",
    "detail": "실적이 나오는 몇 안 되는 코인 중 하나로 긍정적 언급",
    "date": "2025-12-31",
    "ts": "6:11",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "체인링크",
    "dirType": "positive",
    "headline": "체인링크는 저는 오라클 네트워크로 강력할이라고 생각을 합니다.",
    "quote": "체인링크는 저는 오라클 네트워크로 강력할이라고 생각을 합니다.",
    "detail": "오라클 네트워크로서의 체인링크에 대한 강한 신뢰 표명",
    "date": "2025-12-31",
    "ts": "6:15",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "concern",
    "headline": "비트코인도 저는 비트코인이 신이라고 생각 안 합니다. 비트코인은 이제 미신이에요. 미신. ...",
    "quote": "비트코인도 저는 비트코인이 신이라고 생각 안 합니다. 비트코인은 이제 미신이에요. 미신. 여기서 미는 뭐냐? 예. 미국의 미입니다. 네. 미국의 신이에요.",
    "detail": "비트코인이 미국에 종속되어 탈중앙화 정신을 잃었다는 비판적 시각",
    "date": "2025-12-31",
    "ts": "10:45",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "엔비디아",
    "dirType": "buy",
    "headline": "저 같으면 그냥 네. 엔비디아나 아니면 테슬라나 아니면 스페이스엑스 이런 데다 투자를 하지...",
    "quote": "저 같으면 그냥 네. 엔비디아나 아니면 테슬라나 아니면 스페이스엑스 이런 데다 투자를 하지. 왜 비트코인에 투자를 해요?",
    "detail": "비트코인 대신 투자할 대안으로 제시한 종목들 중 하나",
    "date": "2025-12-31",
    "ts": "11:23",
    "url": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "videoUrl": "https://www.youtube.com/watch?v=arOUCh4C9kM",
    "speaker": "코린이 아빠",
    "video_id": "arOUCh4C9kM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "퍼지펭귄",
    "dirType": "buy",
    "headline": "미안하다 펭귄아... 펭귄에서 저 조금 샀어요. 지난 주말에 조금 사 가지고 오늘 보니까 ...",
    "quote": "미안하다 펭귄아... 펭귄에서 저 조금 샀어요. 지난 주말에 조금 사 가지고 오늘 보니까 조금 올랐더라고요. 네 조금 샀습니다. 네 앞으로 더 갈 거 같아 가지고",
    "detail": "화자가 과거에 놓쳤던 퍼지펭귄에 대해 지난 주말에 실제로 매수했다고 밝히면서, 앞으로 더 상승할 것 같다는 전망을 표현",
    "date": "2025-09-07",
    "ts": "5:58",
    "url": "https://www.youtube.com/watch?v=avhNaXmgBeo",
    "videoUrl": "https://www.youtube.com/watch?v=avhNaXmgBeo",
    "speaker": "코린이 아빠",
    "video_id": "avhNaXmgBeo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "모네로",
    "dirType": "positive",
    "headline": "모네로 지금 얘가 시총이 14위까지 올라왔네요. 얘는네 암호화의 끝판왕입니다. 그래서 뭐 ...",
    "quote": "모네로 지금 얘가 시총이 14위까지 올라왔네요. 얘는네 암호화의 끝판왕입니다. 그래서 뭐 아무 아암호화폐라고 하지만 범죄자들이나 이제 마약이나 네. 이런 불법 단체들이 되게 선호하는 거죠. 네. 그래서 얘네들이 지금 되게 잘 나가고 있습니다.",
    "detail": "프라이버시 코인의 특성을 설명하며 시총 14위까지 올라온 점과 현재 잘 나가고 있다고 긍정적으로 평가",
    "date": "2026-01-16",
    "ts": "0:54",
    "url": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "videoUrl": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "speaker": "코린이 아빠",
    "video_id": "awXkJ9hK-a0",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "지캐시",
    "dirType": "positive",
    "headline": "그다음에 GH캐시가 27입니다. 얘가 왜 이렇게 주목받냐? 영영지식 증명이라고 해서 모네로...",
    "quote": "그다음에 GH캐시가 27입니다. 얘가 왜 이렇게 주목받냐? 영영지식 증명이라고 해서 모네로보단 좀 다른 방법인데 여기는 그래도 좀 약간 마일드한 여기는 선택적이라고 합니다.",
    "detail": "지캐시가 시총 27위에 있으며 주목받는 이유를 설명하면서 긍정적으로 언급",
    "date": "2026-01-16",
    "ts": "0:56",
    "url": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "videoUrl": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "speaker": "코린이 아빠",
    "video_id": "awXkJ9hK-a0",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "neutral",
    "headline": "켄토는 절대 달러 패권에 도전하지 않습니다. 미국 정부한테 도전하지 않아요. 그래서 달러 ...",
    "quote": "켄토는 절대 달러 패권에 도전하지 않습니다. 미국 정부한테 도전하지 않아요. 그래서 달러 패권을 강화하는 도구로서 거래에 소각되어 사라지는 허가받은 소각용 코인에 불과합니다.",
    "detail": "캔톤이 다크코인이라는 오해를 해명하며 허가형 블록체인의 특성을 설명. '소각용 코인에 불과하다'고 하지만 전체적으로는 기술적 설명이 중심이며 명확한 매매 의견은 제시하지 않음",
    "date": "2026-01-16",
    "ts": "7:49",
    "url": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "videoUrl": "https://www.youtube.com/watch?v=awXkJ9hK-a0",
    "speaker": "코린이 아빠",
    "video_id": "awXkJ9hK-a0",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "buy",
    "headline": "저는 전통 금융의 효율화라는 것에만 집중하더라도 저는 매우 괜찮은 투자라고 판단했습니다.",
    "quote": "저는 전통 금융의 효율화라는 것에만 집중하더라도 저는 매우 괜찮은 투자라고 판단했습니다.",
    "detail": "전통 금융 효율화 관점에서 CC코인을 긍정적으로 평가하지만, 과거처럼 단기간 급등은 어렵다고 현실적 리스크 언급",
    "date": "2025-12-27",
    "ts": "7:23",
    "url": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "videoUrl": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "speaker": "코린이 아빠",
    "video_id": "axurZUkC5Dc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "positive",
    "headline": "비트코인, 이더리움, 솔라나의 미래 전망은 매우 밝다. 비트코인 전 100만 달러 갈 거라...",
    "quote": "비트코인, 이더리움, 솔라나의 미래 전망은 매우 밝다. 비트코인 전 100만 달러 갈 거라고 생각합니다.",
    "detail": "장기적으로 비트코인이 100만 달러까지 상승할 것으로 전망하며 매우 긍정적인 전망을 제시",
    "date": "2025-12-27",
    "ts": "15:44",
    "url": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "videoUrl": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "speaker": "코린이 아빠",
    "video_id": "axurZUkC5Dc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이더륨 2만 달러 이상 갈 거라고 생각해요. 저는 나중에 수익 창출를 하면 비트코인도 사고...",
    "quote": "이더륨 2만 달러 이상 갈 거라고 생각해요. 저는 나중에 수익 창출를 하면 비트코인도 사고 다시 이더륨도 사고 예 이더리움 많이 매집하고 할 겁니다.",
    "detail": "이더리움의 장기 목표가를 2만 달러 이상으로 보며, 향후 수익 실현 후 재매수 계획을 밝힘",
    "date": "2025-12-27",
    "ts": "15:48",
    "url": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "videoUrl": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "speaker": "코린이 아빠",
    "video_id": "axurZUkC5Dc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "솔라나",
    "dirType": "positive",
    "headline": "그다음에 솔라나도 다 올라갈 거라고 생각합니다.",
    "quote": "그다음에 솔라나도 다 올라갈 거라고 생각합니다.",
    "detail": "비트코인, 이더리움과 함께 솔라나의 장기 전망도 긍정적으로 평가",
    "date": "2025-12-27",
    "ts": "15:51",
    "url": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "videoUrl": "https://www.youtube.com/watch?v=axurZUkC5Dc",
    "speaker": "코린이 아빠",
    "video_id": "axurZUkC5Dc",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "concern",
    "headline": "혹시 어 제 영상을 보고 켄톤에 관심이 가더라도이 투자가 폭망할 수 있다는 점을 꼭 상기하...",
    "quote": "혹시 어 제 영상을 보고 켄톤에 관심이 가더라도이 투자가 폭망할 수 있다는 점을 꼭 상기하시기 바랍니다. 그냥 망할 수도 있어요.",
    "detail": "화자가 캔톤에 대한 설명을 시작하기 전에 투자 리스크에 대해 강하게 경고하고 있음",
    "date": "2025-12-25",
    "ts": "0:52",
    "url": "https://www.youtube.com/watch?v=azTr1P5of4E",
    "videoUrl": "https://www.youtube.com/watch?v=azTr1P5of4E",
    "speaker": "코린이 아빠",
    "video_id": "azTr1P5of4E",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "개인의 거래가 많은 부동산 거래의 경우 이더륨 기반도 저는 매우 강력하다고 보고 있습니다.",
    "quote": "개인의 거래가 많은 부동산 거래의 경우 이더륨 기반도 저는 매우 강력하다고 보고 있습니다.",
    "detail": "RWA 분야에서 이더리움의 가능성을 긍정적으로 평가하되, 절박성 측면에서 한계가 있다고 언급",
    "date": "2025-12-25",
    "ts": "8:59",
    "url": "https://www.youtube.com/watch?v=azTr1P5of4E",
    "videoUrl": "https://www.youtube.com/watch?v=azTr1P5of4E",
    "speaker": "코린이 아빠",
    "video_id": "azTr1P5of4E",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "concern",
    "headline": "RLUSD 자체가 XRP를 혹시 대체할 수 있는 거 아니야... 기술적으로는 RLUSD가 ...",
    "quote": "RLUSD 자체가 XRP를 혹시 대체할 수 있는 거 아니야... 기술적으로는 RLUSD가 같은 용도를 쓸 수 있다는 거예요. 브리치로",
    "detail": "GPT를 통해 학습한 결과, RLUSD가 XRP의 브릿지 역할을 대체할 수 있다는 기술적 가능성에 대한 우려",
    "date": "2025-05-20",
    "ts": "5:17",
    "url": "https://www.youtube.com/watch?v=bLxyJJd_oTg",
    "videoUrl": "https://www.youtube.com/watch?v=bLxyJJd_oTg",
    "speaker": "코린이 아빠",
    "video_id": "bLxyJJd_oTg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "알트코인",
    "dirType": "positive",
    "headline": "지금 알트코인들이 난리가 났죠. 암호화폐 산법이 통과가 됐어요.",
    "quote": "지금 알트코인들이 난리가 났죠. 암호화폐 산법이 통과가 됐어요.",
    "detail": "크립토 3법 하원 통과로 인한 알트코인 시장 상승을 긍정적으로 평가",
    "date": "2025-07-18",
    "ts": "0:14",
    "url": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "videoUrl": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "speaker": "코린이 아빠",
    "video_id": "bP58fA9rzzo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "스테이블코인",
    "dirType": "positive",
    "headline": "스테이블 코인을 앞으로 육성하겠다라는 겁니다. 스테이블 코인이 많이 나올 겁니다.",
    "quote": "스테이블 코인을 앞으로 육성하겠다라는 겁니다. 스테이블 코인이 많이 나올 겁니다.",
    "detail": "크립토 3법 통과로 스테이블 코인 시장 육성 정책이 확정되어 향후 성장 전망 긍정적",
    "date": "2025-07-18",
    "ts": "0:28",
    "url": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "videoUrl": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "speaker": "코린이 아빠",
    "video_id": "bP58fA9rzzo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "buy",
    "headline": "XRP 비중이 제일 높기 때문에 자 지금 2,800원에서부터 쭉 올라와서 오늘 아침에 5,...",
    "quote": "XRP 비중이 제일 높기 때문에 자 지금 2,800원에서부터 쭉 올라와서 오늘 아침에 5,000원을 드디어 찍었죠. 저도 마찬가지죠.",
    "detail": "화자가 XRP 최대 비중으로 보유하고 있으며 상승 수익을 실현하고 있다고 언급",
    "date": "2025-07-18",
    "ts": "1:46",
    "url": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "videoUrl": "https://www.youtube.com/watch?v=bP58fA9rzzo",
    "speaker": "코린이 아빠",
    "video_id": "bP58fA9rzzo",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "폭발할 거라 믿어 의심지 않습니다",
    "quote": "폭발할 거라 믿어 의심지 않습니다",
    "detail": "이더리움의 폭발론 근거로 비탈릭 부텔린의 리더십, 12월 3일 푸사카 업데이트, 기관의 보유자산화, ETF 도입 등을 제시하며 강한 확신 표현",
    "date": "2025-11-20",
    "ts": "4:18",
    "url": "https://www.youtube.com/watch?v=bi8ZfEB2mZ4",
    "videoUrl": "https://www.youtube.com/watch?v=bi8ZfEB2mZ4",
    "speaker": "코린이 아빠",
    "video_id": "bi8ZfEB2mZ4",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "폭발할 거라 믿어 의심지 않습니다",
    "quote": "폭발할 거라 믿어 의심지 않습니다",
    "detail": "BMR을 열광하는 월가 세력들, 아크 인베스트먼트, 블랙록, 피델러티 등 기관들의 매입을 근거로 강한 확신 표현",
    "date": "2025-11-20",
    "ts": "4:18",
    "url": "https://www.youtube.com/watch?v=bi8ZfEB2mZ4",
    "videoUrl": "https://www.youtube.com/watch?v=bi8ZfEB2mZ4",
    "speaker": "코린이 아빠",
    "video_id": "bi8ZfEB2mZ4",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "제가 보니까 그래요. 주린이는 코인을 몰라서 그다음에 코리니는 주식을 몰라서 RW가 참 어...",
    "quote": "제가 보니까 그래요. 주린이는 코인을 몰라서 그다음에 코리니는 주식을 몰라서 RW가 참 어려운 개념입니다. 네. 어려워요. 그래서 RW의 위력을 먼저 여러분들 한번 공부를 해 보세요. 그러면 캔톤이 보이실 겁니다. 네. 자, 다음 시간에는 제가 당분간 역시 캔톤만 다룰 겁니다. 전 미쳤거든요.",
    "detail": "DTCC와 캔톤네트워크의 미국 국채 토큰화 협력, SEC 승인, 전통 금융기관들의 캔톤 재단 참여 등을 종합적으로 분석한 후 캔톤에 대한 강한 확신을 표현. 화자가 '미쳤다'고 표현할 정도로 강한 신념을 보임",
    "date": "2025-12-18",
    "ts": "10:24",
    "url": "https://www.youtube.com/watch?v=bm_O5iqGiFg",
    "videoUrl": "https://www.youtube.com/watch?v=bm_O5iqGiFg",
    "speaker": "코린이 아빠",
    "video_id": "bm_O5iqGiFg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "concern",
    "headline": "비트마인이 너무 많이 올랐다라고 생각하면 거기에 추매를 하거나 하는 거는 좀 지향하셔야 될...",
    "quote": "비트마인이 너무 많이 올랐다라고 생각하면 거기에 추매를 하거나 하는 거는 좀 지향하셔야 될 것 같습니다",
    "detail": "비트마인이 20% 상승한 상황에서 이더리움이 동반 상승하지 않아 혼자서는 지속적 상승이 어렵다는 분석과 함께 추매 경고",
    "date": "2025-11-25",
    "ts": "1:27",
    "url": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "videoUrl": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "speaker": "코린이 아빠",
    "video_id": "dD0eVCXS7fg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "이더리움의 미래에는 저는 슈퍼사이클만 있다고 생각을 합니다",
    "quote": "이더리움의 미래에는 저는 슈퍼사이클만 있다고 생각을 합니다",
    "detail": "반감기와 무관하게 스테이블코인과 대기업 코인 출시로 인한 시장 파이 확장으로 장기적 슈퍼사이클 전망",
    "date": "2025-11-25",
    "ts": "8:34",
    "url": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "videoUrl": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "speaker": "코린이 아빠",
    "video_id": "dD0eVCXS7fg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "concern",
    "headline": "이더륨의 상승을 누르고 있는 거는 비트코인이다라고 얘기를 해요",
    "quote": "이더륨의 상승을 누르고 있는 거는 비트코인이다라고 얘기를 해요",
    "detail": "비트코인 장기 홀더들의 매도와 4년 사이클 종료 인식으로 인해 이더리움과 비트마인의 상승을 제약하고 있다는 분석",
    "date": "2025-11-25",
    "ts": "1:43",
    "url": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "videoUrl": "https://www.youtube.com/watch?v=dD0eVCXS7fg",
    "speaker": "코린이 아빠",
    "video_id": "dD0eVCXS7fg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "positive",
    "headline": "미래를 바꿀 수 있는 것들 네, 이더륨, 비트마인 예,요 분명히 세상을 바꿀 수 있다고 생...",
    "quote": "미래를 바꿀 수 있는 것들 네, 이더륨, 비트마인 예,요 분명히 세상을 바꿀 수 있다고 생각을 하고",
    "detail": "화자가 미래 지향적 투자 철학을 설명하며 이더리움이 세상을 바꿀 수 있는 기술이라고 긍정적으로 평가",
    "date": "2025-10-19",
    "ts": "9:44",
    "url": "https://www.youtube.com/watch?v=e7Pd9dn7uic",
    "videoUrl": "https://www.youtube.com/watch?v=e7Pd9dn7uic",
    "speaker": "코린이 아빠",
    "video_id": "e7Pd9dn7uic",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "미래를 바꿀 수 있는 것들 네, 이더륨, 비트마인 예,요 분명히 세상을 바꿀 수 있다고 생...",
    "quote": "미래를 바꿀 수 있는 것들 네, 이더륨, 비트마인 예,요 분명히 세상을 바꿀 수 있다고 생각을 하고",
    "detail": "화자가 미래 지향적 투자 철학을 설명하며 비트마인이 세상을 바꿀 수 있는 기술이라고 긍정적으로 평가",
    "date": "2025-10-19",
    "ts": "9:44",
    "url": "https://www.youtube.com/watch?v=e7Pd9dn7uic",
    "videoUrl": "https://www.youtube.com/watch?v=e7Pd9dn7uic",
    "speaker": "코린이 아빠",
    "video_id": "e7Pd9dn7uic",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "concern",
    "headline": "비트코인 4년 사이클 설 여전히 유효할까? 저는 그 초부터 올해 초부터 그 얘기를 했죠. ...",
    "quote": "비트코인 4년 사이클 설 여전히 유효할까? 저는 그 초부터 올해 초부터 그 얘기를 했죠. 네. 사이클 설은 유효하지 않다.",
    "detail": "비트코인의 전통적인 4년 사이클 이론이 더 이상 작동하지 않는다는 분석",
    "date": "2025-12-25",
    "ts": "1:40",
    "url": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "videoUrl": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "speaker": "코린이 아빠",
    "video_id": "haqNGCpQKDg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "알트코인",
    "dirType": "strong_sell",
    "headline": "2026년도에 대부분의 알트코인은 다 멸망하리라고 예상하고 있습니다. 다 망할 것이다.",
    "quote": "2026년도에 대부분의 알트코인은 다 멸망하리라고 예상하고 있습니다. 다 망할 것이다.",
    "detail": "알트코인 시장의 구조적 변화와 빅테크 진출로 인한 기존 알트코인들의 멸망 예측",
    "date": "2025-12-25",
    "ts": "2:47",
    "url": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "videoUrl": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "speaker": "코린이 아빠",
    "video_id": "haqNGCpQKDg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "concern",
    "headline": "달러 스테이블 코인의 수혜주가 무조건 이더리움이 될 거라고 생각을 했는데 이제 그게 아니라...",
    "quote": "달러 스테이블 코인의 수혜주가 무조건 이더리움이 될 거라고 생각을 했는데 이제 그게 아니라는 거를 단초를 제가 발견을 하면서부터 그때부터 흔들리기 시작한 겁니다.",
    "detail": "스테이블코인 활성화가 이더리움에게 예상보다 큰 수혜를 주지 않을 것이라는 분석",
    "date": "2025-12-25",
    "ts": "4:54",
    "url": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "videoUrl": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "speaker": "코린이 아빠",
    "video_id": "haqNGCpQKDg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "저는 X 잡코인 그다음에 X 잡추. 예. 예. 여러분 다 아시죠? 네. 이거에 미쳐 있죠....",
    "quote": "저는 X 잡코인 그다음에 X 잡추. 예. 예. 여러분 다 아시죠? 네. 이거에 미쳐 있죠... 저는이 잡코인하고 잡주에 미쳐 있죠.",
    "detail": "화자가 CC코인에 강한 확신을 보이며 집중 투자하고 있다는 표현",
    "date": "2025-12-25",
    "ts": "11:16",
    "url": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "videoUrl": "https://www.youtube.com/watch?v=haqNGCpQKDg",
    "speaker": "코린이 아빠",
    "video_id": "haqNGCpQKDg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "hold",
    "headline": "저는 CC코인에 대해서 저는 단기 투자가 아니라 이제 장기 투자를 목표를 하고 있습니다.",
    "quote": "저는 CC코인에 대해서 저는 단기 투자가 아니라 이제 장기 투자를 목표를 하고 있습니다.",
    "detail": "화자는 CC코인을 대한민국의 지정학적 리스크에 대한 헤지 자산으로 보고 장기 보유 계획을 밝힘",
    "date": "2026-01-15",
    "ts": "6:53",
    "url": "https://www.youtube.com/watch?v=hr5v-QUws9c",
    "videoUrl": "https://www.youtube.com/watch?v=hr5v-QUws9c",
    "speaker": "코린이 아빠",
    "video_id": "hr5v-QUws9c",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "sell",
    "headline": "공포에 못 버텼습니다. 조금 팔았어요. 한 10% 15% 정도 팔았습니다.",
    "quote": "공포에 못 버텼습니다. 조금 팔았어요. 한 10% 15% 정도 팔았습니다.",
    "detail": "이더리움이 3,000달러 무너질 뻔하는 상황에서 공포로 인해 직접 매도 행동을 취함",
    "date": "2025-11-04",
    "ts": "0:51",
    "url": "https://www.youtube.com/watch?v=iAZogOLzUxg",
    "videoUrl": "https://www.youtube.com/watch?v=iAZogOLzUxg",
    "speaker": "코린이 아빠",
    "video_id": "iAZogOLzUxg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "concern",
    "headline": "제 비트마인도 음전으로 전환 당했습니다. 강제적으로 전환 당했죠.",
    "quote": "제 비트마인도 음전으로 전환 당했습니다. 강제적으로 전환 당했죠.",
    "detail": "플러스 2억까지 갔던 비트마인이 음전으로 강제 전환되는 상황 발생",
    "date": "2025-11-04",
    "ts": "1:00",
    "url": "https://www.youtube.com/watch?v=iAZogOLzUxg",
    "videoUrl": "https://www.youtube.com/watch?v=iAZogOLzUxg",
    "speaker": "코린이 아빠",
    "video_id": "iAZogOLzUxg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "월가의 큰 손들이네 직접 만들었습니다. 골드만 삭스가 가장 대표적인 파트너고 그다음에네 프...",
    "quote": "월가의 큰 손들이네 직접 만들었습니다. 골드만 삭스가 가장 대표적인 파트너고 그다음에네 프랑스 최고의 은행 도이치뱅크부터 해가죠. 독일 최대 은행 그리고 시카고 옵션 거래소. 예. 거대한 기업들이 지금 다 들어와 있죠.",
    "detail": "화자가 CC코인(캔톤네트워크)을 소개하면서 월가 대형 금융기관들이 참여하고 있다는 점을 강조. 하지만 투자 주의를 당부하고 다음 영상에서 허점을 다룰 것이라고 예고하며 hedged 발언",
    "date": "2025-11-27",
    "ts": "1:44",
    "url": "https://www.youtube.com/watch?v=ijzQXeQv8co",
    "videoUrl": "https://www.youtube.com/watch?v=ijzQXeQv8co",
    "speaker": "코린이 아빠",
    "video_id": "ijzQXeQv8co",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "제가 드디어 XRP 만개를 팔아서 어 국장에 들어갔습니다",
    "quote": "제가 드디어 XRP 만개를 팔아서 어 국장에 들어갔습니다",
    "detail": "화자가 XRP 1만개를 실제로 매도하여 한국 주식 시장에 투자했다고 직접 언급",
    "date": "2025-06-15",
    "ts": "0:13",
    "url": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "videoUrl": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "speaker": "코린이 아빠",
    "video_id": "jA8ngycEQNE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "삼성이엔지니어링",
    "dirType": "buy",
    "headline": "삼성 ENA 아, 네. 여기 정말 추천해 드리는데이 플러스예요. 네. 한번 공부 한번 해 ...",
    "quote": "삼성 ENA 아, 네. 여기 정말 추천해 드리는데이 플러스예요. 네. 한번 공부 한번 해 보세요. 되게 좋은 기업입니다",
    "detail": "화자가 삼성이엔지니어링을 직접 추천하며 좋은 기업이라고 평가, 본인도 투자하여 수익 중",
    "date": "2025-06-15",
    "ts": "0:53",
    "url": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "videoUrl": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "speaker": "코린이 아빠",
    "video_id": "jA8ngycEQNE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "코스피",
    "dirType": "buy",
    "headline": "한국 주식 시장은 네, 기조적 변화다. 일시적인 상승이 아니다라는 얘기를 해요. 지금 거버...",
    "quote": "한국 주식 시장은 네, 기조적 변화다. 일시적인 상승이 아니다라는 얘기를 해요. 지금 거버넌스이 구조가 바뀌고 있기 때문에 앞으로 많은 기대가 된다는 거예요",
    "detail": "한국 주식 시장의 구조적 변화(상법 개정, 코리아 디스카운트 해소)를 근거로 장기 상승을 전망하며, 본인도 XRP를 매도하여 한국 주식에 투자",
    "date": "2025-06-15",
    "ts": "5:37",
    "url": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "videoUrl": "https://www.youtube.com/watch?v=jA8ngycEQNE",
    "speaker": "코린이 아빠",
    "video_id": "jA8ngycEQNE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "strong_buy",
    "headline": "지금까지 이런 치킨 아닌 아, 투자 종목은 없었다. 마음 편한 기다림의 미하 캔톤 타리면 ...",
    "quote": "지금까지 이런 치킨 아닌 아, 투자 종목은 없었다. 마음 편한 기다림의 미하 캔톤 타리면 가자... 저 역시 마찬가지입니다. 지금까지 이렇게 마음 편한 투자는 저도 없었던 것 같습니다.",
    "detail": "JP모건의 JPM 토큰이 캔톤 네트워크와 연결되는 뉴스를 바탕으로, 캔톤의 기술적 우위와 성장 가능성을 강조하며 극도로 확신에 찬 투자 추천을 표현. 화자가 직접 '마음 편한 투자'라며 개인적 확신을 드러냄",
    "date": "2026-01-11",
    "ts": "7:09",
    "url": "https://www.youtube.com/watch?v=jRE3eC8gx8o",
    "videoUrl": "https://www.youtube.com/watch?v=jRE3eC8gx8o",
    "speaker": "코린이 아빠",
    "video_id": "jRE3eC8gx8o",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "neutral",
    "headline": "조정 구간이다라고 생각이 되고 그다음에 뭐 또 갈 수도 있고 더 떨어질 수도 있고 그렇겠죠...",
    "quote": "조정 구간이다라고 생각이 되고 그다음에 뭐 또 갈 수도 있고 더 떨어질 수도 있고 그렇겠죠. 네. 뭐 제가 뭐 그런 건 모르니까",
    "detail": "한 달간 2배 상승 후 하락에 대해 조정으로 보지만 향후 방향성에 대해서는 판단을 유보함",
    "date": "2026-01-06",
    "ts": "2:38",
    "url": "https://www.youtube.com/watch?v=mMCVfDBaFKA",
    "videoUrl": "https://www.youtube.com/watch?v=mMCVfDBaFKA",
    "speaker": "코린이 아빠",
    "video_id": "mMCVfDBaFKA",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "마이크로스트래티지",
    "dirType": "concern",
    "headline": "비트코인 같은 경우는 64,000달러까지 왔고 지금 이게 어 6만 달러가 만약에 무너지면 ...",
    "quote": "비트코인 같은 경우는 64,000달러까지 왔고 지금 이게 어 6만 달러가 만약에 무너지면 이제 마이크로스트가 좀 위험하다는 얘기가 있습니다",
    "detail": "비트코인 6만 달러 선이 무너질 경우 전환사채를 통한 자본 조달로 인한 부채 리스크 우려",
    "date": "2026-02-06",
    "ts": "0:42",
    "url": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "videoUrl": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "speaker": "코린이 아빠",
    "video_id": "oC-mHWKj8m8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "비트마인 같은 경우는 이제 주식을 통해서 했었기 때문에 좀 더 안전하다고 할 수 있겠지만",
    "quote": "비트마인 같은 경우는 이제 주식을 통해서 했었기 때문에 좀 더 안전하다고 할 수 있겠지만",
    "detail": "마이크로스트래티지 대비 상대적으로 안전한 자금 조달 구조를 언급하며 긍정적 평가",
    "date": "2026-02-06",
    "ts": "0:54",
    "url": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "videoUrl": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "speaker": "코린이 아빠",
    "video_id": "oC-mHWKj8m8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 ...",
    "quote": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 시리즈 올려 가지고",
    "detail": "한 달 전 3대 탈출 시리즈를 통해 XRP 매도를 권유했다고 언급",
    "date": "2026-02-06",
    "ts": "6:27",
    "url": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "videoUrl": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "speaker": "코린이 아빠",
    "video_id": "oC-mHWKj8m8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트코인",
    "dirType": "sell",
    "headline": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 ...",
    "quote": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 시리즈 올려 가지고",
    "detail": "한 달 전 3대 탈출 시리즈를 통해 비트코인 매도를 권유했다고 언급",
    "date": "2026-02-06",
    "ts": "6:27",
    "url": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "videoUrl": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "speaker": "코린이 아빠",
    "video_id": "oC-mHWKj8m8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "sell",
    "headline": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 ...",
    "quote": "제가 한 달 전에 XR 그 3대 탈출 시리즈 올렸잖아요. XRP하고 비트하고 이더류 탈출 시리즈 올려 가지고",
    "detail": "한 달 전 3대 탈출 시리즈를 통해 이더리움 매도를 권유했다고 언급",
    "date": "2026-02-06",
    "ts": "6:27",
    "url": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "videoUrl": "https://www.youtube.com/watch?v=oC-mHWKj8m8",
    "speaker": "코린이 아빠",
    "video_id": "oC-mHWKj8m8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "buy",
    "headline": "아예 내 의견으로는 야 정말 훌륭한 시간이다. 어 ETF 그 이더리움을 담기에 너무 좋은 ...",
    "quote": "아예 내 의견으로는 야 정말 훌륭한 시간이다. 어 ETF 그 이더리움을 담기에 너무 좋은 시간이야",
    "detail": "에릭 트럼프가 2025년 2월 4일 X에 올린 이더리움 매수 추천 발언을 인용하며, 실제로 저점에서 매수한 후 X에 올린 것으로 분석",
    "date": "2025-07-18",
    "ts": "0:37",
    "url": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "videoUrl": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "speaker": "코린이 아빠",
    "video_id": "p2cJUnTXVPE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "솔라나",
    "dirType": "positive",
    "headline": "탈 중앙하고 성숙한 그 네트워크를 활용해야 된다고 하는데이 조건 안에 들어가는게 세 가지밖...",
    "quote": "탈 중앙하고 성숙한 그 네트워크를 활용해야 된다고 하는데이 조건 안에 들어가는게 세 가지밖에 없어요. 이더리움, 솔라나, 리플입니다",
    "detail": "크립토 3법 조건을 만족하는 성숙한 네트워크가 3개뿐이라는 분석에서 솔라나가 포함",
    "date": "2025-07-18",
    "ts": "3:22",
    "url": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "videoUrl": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "speaker": "코린이 아빠",
    "video_id": "p2cJUnTXVPE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "neutral",
    "headline": "물론 XRP는 굉장히 강력합니다. 네. 진짜 전송도 정말 빠르고... 100달러도 갈 수 ...",
    "quote": "물론 XRP는 굉장히 강력합니다. 네. 진짜 전송도 정말 빠르고... 100달러도 갈 수 있고 1,000달러도 갈 수 있겠죠. 만약에 XRP가 이걸 다 물리쳤다 그러면 진짜 1,000달러 갈 수도 있겠죠. 어, 모르는 겁니다",
    "detail": "XRP의 강점을 인정하면서도 은행들과의 경쟁 결과에 따라 달라질 것이라며 불확실성 언급",
    "date": "2025-07-18",
    "ts": "5:55",
    "url": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "videoUrl": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "speaker": "코린이 아빠",
    "video_id": "p2cJUnTXVPE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "서클",
    "dirType": "positive",
    "headline": "USDC 기반으로 하려고 하기 때문에 서클이 엄청나게 폭등을 한 거죠. 네. 30달러였던 ...",
    "quote": "USDC 기반으로 하려고 하기 때문에 서클이 엄청나게 폭등을 한 거죠. 네. 30달러였던 서클이 지금 뭐 230달러 이러죠",
    "detail": "USDC 중심의 스테이블코인 정책으로 서클이 대폭 상승했다는 긍정적 현황 분석",
    "date": "2025-07-18",
    "ts": "4:22",
    "url": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "videoUrl": "https://www.youtube.com/watch?v=p2cJUnTXVPE",
    "speaker": "코린이 아빠",
    "video_id": "p2cJUnTXVPE",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "저는 참고로 XRP를 전부 다 매도를 했고요. 4,500원에서 5,000원 대에서 전부 다...",
    "quote": "저는 참고로 XRP를 전부 다 매도를 했고요. 4,500원에서 5,000원 대에서 전부 다 매도를 했습니다",
    "detail": "화자가 본인의 XRP 전량 매도 사실을 공개하여 매도 신호를 간접적으로 전달",
    "date": "2026-01-03",
    "ts": "0:51",
    "url": "https://www.youtube.com/watch?v=pN4qDs7Zfh8",
    "videoUrl": "https://www.youtube.com/watch?v=pN4qDs7Zfh8",
    "speaker": "코린이 아빠",
    "video_id": "pN4qDs7Zfh8",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "sell",
    "headline": "저는 BM을 패닉스을 했습니다... -6,300에 전부 손절 처리했습니다. 그래서 일단 저...",
    "quote": "저는 BM을 패닉스을 했습니다... -6,300에 전부 손절 처리했습니다. 그래서 일단 저는 홀딩입니다.",
    "detail": "중국 AI(키미 K2)의 GPT 능가 성능에 대한 우려와 AI 버블 붕괴 가능성에 따른 패닉 매도 실행",
    "date": "2025-11-13",
    "ts": "4:05",
    "url": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "videoUrl": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "speaker": "코린이 아빠",
    "video_id": "pTX3bb53q4w",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "이더리움",
    "dirType": "hold",
    "headline": "저는 이더리움 그 스테이킹 한 거하고 이더륨 현물만 일단은 유지를 하고",
    "quote": "저는 이더리움 그 스테이킹 한 거하고 이더륨 현물만 일단은 유지를 하고",
    "detail": "미국 주식은 매각했지만 이더리움은 변동성이 상대적으로 작다고 판단하여 보유 유지",
    "date": "2025-11-13",
    "ts": "4:22",
    "url": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "videoUrl": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "speaker": "코린이 아빠",
    "video_id": "pTX3bb53q4w",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "미국 주식",
    "dirType": "neutral",
    "headline": "미국 주식에 대한 배팅은 관망하기로 결정했습니다",
    "quote": "미국 주식에 대한 배팅은 관망하기로 결정했습니다",
    "detail": "AI 패권 경쟁의 불확실성과 중국 AI 기술 발전에 따른 시장 전망 불투명으로 관망 결정",
    "date": "2025-11-13",
    "ts": "4:38",
    "url": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "videoUrl": "https://www.youtube.com/watch?v=pTX3bb53q4w",
    "speaker": "코린이 아빠",
    "video_id": "pTX3bb53q4w",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "켄톤이 잡코인이다, 자발트다 뭐 이런 얘기 하는데 좀 공부 좀 하시고 알아보고 이런 얘기를...",
    "quote": "켄톤이 잡코인이다, 자발트다 뭐 이런 얘기 하는데 좀 공부 좀 하시고 알아보고 이런 얘기를 했으면 좋겠습니다. DTCC가 미국의 중앙 예탁 결정원입니다. 디지털 에셋 켄톤이 2024년도에 미국 국채 담보 관리를 규제 샌드박스로 테스트를 완료했습니다. 미국 국채를 실제로 여기서 발행을 해 가지고 이게 담보 관리가 어떻게 되는지를 테스트해 가지고 성공을 했어요.",
    "detail": "연준 회의에서 캔톤네트워크가 직접 소개되고 DTCC와의 실제 테스트 완료를 근거로 캔톤에 대한 강한 긍정적 전망을 표현. 잡코인이라는 의견을 강하게 반박하며 실질적 성과를 강조",
    "date": "2025-12-12",
    "ts": "11:17",
    "url": "https://www.youtube.com/watch?v=qKzql5TOQkg",
    "videoUrl": "https://www.youtube.com/watch?v=qKzql5TOQkg",
    "speaker": "코린이 아빠",
    "video_id": "qKzql5TOQkg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "서클",
    "dirType": "positive",
    "headline": "서클의 주가가 높은 거죠. 그런 그이자 수익이 발생을 하기 때문에",
    "quote": "서클의 주가가 높은 거죠. 그런 그이자 수익이 발생을 하기 때문에",
    "detail": "USDC 발행사인 서클이 미국 국채 운용을 통한 이자 수익 구조로 인해 주가가 높다고 분석하며 긍정적 전망",
    "date": "2025-12-12",
    "ts": "5:51",
    "url": "https://www.youtube.com/watch?v=qKzql5TOQkg",
    "videoUrl": "https://www.youtube.com/watch?v=qKzql5TOQkg",
    "speaker": "코린이 아빠",
    "video_id": "qKzql5TOQkg",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캐톤네트워크",
    "dirType": "concern",
    "headline": "CC코인의 치명적인 약점에 대해서 제가 한번 말씀드리도록 하겠습니다. 개미들은 어, CC ...",
    "quote": "CC코인의 치명적인 약점에 대해서 제가 한번 말씀드리도록 하겠습니다. 개미들은 어, CC 코인에 투자만 할 수 있을 뿐입니다. 노드 운영은 오직 허가받은 기관만 가능합니다. 개인은이 CC 코인으로 활용할 수 있는 활용 수산이 전혀 없습니다.",
    "detail": "CC코인의 구조적 문제점을 지적하며 개인투자자에게는 활용도가 전혀 없다고 경고",
    "date": "2025-11-28",
    "ts": "0:07",
    "url": "https://www.youtube.com/watch?v=r0DKsSOaSR0",
    "videoUrl": "https://www.youtube.com/watch?v=r0DKsSOaSR0",
    "speaker": "코린이 아빠",
    "video_id": "r0DKsSOaSR0",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "positive",
    "headline": "피터티 팔 것도 결코 악재가 아니라는 거 반드시 말씀을 드립니다",
    "quote": "피터티 팔 것도 결코 악재가 아니라는 거 반드시 말씀을 드립니다",
    "detail": "피터 틸의 지분 매각이 악재가 아니라고 강조하며, 이는 벤처투자 회사의 일반적인 익절 패턴이라고 설명",
    "date": "2025-11-14",
    "ts": "5:21",
    "url": "https://www.youtube.com/watch?v=rOCkK9x9UyY",
    "videoUrl": "https://www.youtube.com/watch?v=rOCkK9x9UyY",
    "speaker": "코린이 아빠",
    "video_id": "rOCkK9x9UyY",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "sell",
    "headline": "저는 XRP 100% 다 팔았어요. 한 한 개도 남아 있지 않습니다. 그리고 저도 사지도 ...",
    "quote": "저는 XRP 100% 다 팔았어요. 한 한 개도 남아 있지 않습니다. 그리고 저도 사지도 않을 거예요. 더 이상.",
    "detail": "화자가 XRP에 대한 7가지 의심점을 제시하며 전량 매도했다고 밝힘. 리플과 XRP 분리, SBI 투자가 토큰이 아닌 주식, RLUSD 개발로 XRP 필요성 감소, IPO 계획, 창업자 익절, CEO 복장 등을 근거로 제시",
    "date": "2025-08-01",
    "ts": "7:11",
    "url": "https://www.youtube.com/watch?v=v-w9X2m2V1s",
    "videoUrl": "https://www.youtube.com/watch?v=v-w9X2m2V1s",
    "speaker": "코린이 아빠",
    "video_id": "v-w9X2m2V1s",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "SBI홀딩스",
    "dirType": "buy",
    "headline": "그리고 저는 리플을 담았습니다. SBI 홀딩스를 가시면 돼요. 저는 SBI 홀딩스가 떡상할...",
    "quote": "그리고 저는 리플을 담았습니다. SBI 홀딩스를 가시면 돼요. 저는 SBI 홀딩스가 떡상할 수도 있다라고 생각을 하고 있습니다.",
    "detail": "XRP를 전량 매도하고 대신 리플 지분 8-9%를 보유한 SBI홀딩스에 투자. 리플 IPO시 수혜 기대하지만 '가설'이라고 언급하며 불확실성 표현",
    "date": "2025-08-01",
    "ts": "7:15",
    "url": "https://www.youtube.com/watch?v=v-w9X2m2V1s",
    "videoUrl": "https://www.youtube.com/watch?v=v-w9X2m2V1s",
    "speaker": "코린이 아빠",
    "video_id": "v-w9X2m2V1s",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "비트마인",
    "dirType": "concern",
    "headline": "비트마인도 결국에는 목표 5%를 확보하려면 자산 증자로 인한 주가 희석을 피할 수 없어",
    "quote": "비트마인도 결국에는 목표 5%를 확보하려면 자산 증자로 인한 주가 희석을 피할 수 없어",
    "detail": "비트마인의 구조적 문제인 주가 희석 이슈를 언급하며 우려를 표현",
    "date": "2025-08-10",
    "ts": "1:25",
    "url": "https://www.youtube.com/watch?v=wpmzTlu5JcI",
    "videoUrl": "https://www.youtube.com/watch?v=wpmzTlu5JcI",
    "speaker": "코린이 아빠",
    "video_id": "wpmzTlu5JcI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "샤프링크",
    "dirType": "concern",
    "headline": "파도타기를 기꺼이 즐기실 분이라면 하셔도 뭐 무방하다고 생각이 돼요. 사실 저도 샤프링크 ...",
    "quote": "파도타기를 기꺼이 즐기실 분이라면 하셔도 뭐 무방하다고 생각이 돼요. 사실 저도 샤프링크 조금 사 놓은게 있습니다. 아직 마이너스거든요. 거친 파도에 쓰러지지 않도록 적당한 물량으로만 즐기시길 권장해 드리겠습니다. 파도가 좀 셀 거예요",
    "detail": "파도타기 전략을 인정하면서도 변동성이 클 것이라는 경고를 함께 제시. 본인도 보유 중",
    "date": "2025-08-10",
    "ts": "4:39",
    "url": "https://www.youtube.com/watch?v=wpmzTlu5JcI",
    "videoUrl": "https://www.youtube.com/watch?v=wpmzTlu5JcI",
    "speaker": "코린이 아빠",
    "video_id": "wpmzTlu5JcI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "타르",
    "dirType": "hold",
    "headline": "1월 30일까지 켄토는 공식적으로 아직 바이오 기업입니다. 따라서 아직 그들의 매집 전략은...",
    "quote": "1월 30일까지 켄토는 공식적으로 아직 바이오 기업입니다. 따라서 아직 그들의 매집 전략은 저는 출발도 하지 않았다라고 보고 있습니다",
    "detail": "1월 30일 주주총회까지는 아직 공식적으로 바이오 기업이므로 매집 전략이 시작되지 않았다는 분석",
    "date": "2026-01-14",
    "ts": "10:29",
    "url": "https://www.youtube.com/watch?v=wyTxEHlToOM",
    "videoUrl": "https://www.youtube.com/watch?v=wyTxEHlToOM",
    "speaker": "코린이 아빠",
    "video_id": "wyTxEHlToOM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "1월 30일 이후 드디어 바이오 기업에서 CC코인 전략적 매집 회사로 공식화가 된다라고 볼...",
    "quote": "1월 30일 이후 드디어 바이오 기업에서 CC코인 전략적 매집 회사로 공식화가 된다라고 볼 수가 있습니다",
    "detail": "주주총회 통과 이후 THAR이 공식적으로 CC코인 매집 회사가 되어 추가 매집으로 코인 가치 상승 기대",
    "date": "2026-01-14",
    "ts": "7:59",
    "url": "https://www.youtube.com/watch?v=wyTxEHlToOM",
    "videoUrl": "https://www.youtube.com/watch?v=wyTxEHlToOM",
    "speaker": "코린이 아빠",
    "video_id": "wyTxEHlToOM",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "캔톤네트워크",
    "dirType": "positive",
    "headline": "CC코인 매집 회사는 정확한 투자 지분도 공개를 안 하고 있어요. 얘네가 예를 들면 뭐 5...",
    "quote": "CC코인 매집 회사는 정확한 투자 지분도 공개를 안 하고 있어요. 얘네가 예를 들면 뭐 5억 3천만 달러 중에 우리는 얼마, 우리는 얼마, 우리는 얼마 이런 거 없어요. 공개 전혀 안 합니다. 그다음에 CC코인의 정확한 매집량도 공개하지 않죠. 얘네는 완전 비밀주의예요. 독점 기업은 스스로를 결코 독점이라 말하지 않는다. CC 코인은 단지 금융 기관의 수수료 코인일 뿐입니다.",
    "detail": "화자는 CC코인을 구글과 같은 독점기업의 예시로 제시하며, 비밀주의적 운영과 겸손한 태도가 실제로는 독점적 지위를 나타내는 신호라고 분석. 5억 3천만 달러 투자를 받았지만 투자 지분과 매집량을 공개하지 않는 것을 긍정적 신호로 해석",
    "date": "2025-12-08",
    "ts": "7:43",
    "url": "https://www.youtube.com/watch?v=y2CCjhxS1QI",
    "videoUrl": "https://www.youtube.com/watch?v=y2CCjhxS1QI",
    "speaker": "코린이 아빠",
    "video_id": "y2CCjhxS1QI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  },
  {
    "stock": "XRP",
    "dirType": "concern",
    "headline": "막상 이제 조사를 해 보면 XRP에 전혀 관심이 없죠. 트럼프 재단을. 그래서 트럼프 미디...",
    "quote": "막상 이제 조사를 해 보면 XRP에 전혀 관심이 없죠. 트럼프 재단을. 그래서 트럼프 미디어는 지금 비트코인에 올인하고 있고 비트코인은 올인하고 있고 그다음에 트럼프 개인및 가족 지갑을 이렇게 보면 거의 이제 이더리움 기반하고 자체 프로젝트. XRP하고 전혀 관계가 없다는 거. 자기가 마치 세계 금융계를 꽉 잡은 것처럼네 구라를 뜹니다.",
    "detail": "화자는 과거 XRP에 100% 올인했던 경험을 바탕으로, 트럼프와의 연관성을 과장 홍보하는 XRP의 마케팅을 비판. 실제로는 트럼프가 비트코인과 이더리움에만 관심이 있다고 지적하며 XRP의 과대광고를 경고",
    "date": "2025-12-08",
    "ts": "9:35",
    "url": "https://www.youtube.com/watch?v=y2CCjhxS1QI",
    "videoUrl": "https://www.youtube.com/watch?v=y2CCjhxS1QI",
    "speaker": "코린이 아빠",
    "video_id": "y2CCjhxS1QI",
    "influencer": "코린이 아빠",
    "influencer_id": 99
  }
];